### ISSUE TITLE
When sending money on mac, sometimes the app will crash

### ISSUE THREAD

**Issue by samuelandert** [duniter/sakia#322]
``` fish
DEBUG:wallet:send_money:Key : *****key***** :  ***********************
DEBUG:wallet:send_money:Sender pubkey:7NoTJK95DYPDMpoad9obDPqXFW5JEXxmz4cyg39j5goQ
DEBUG:wallet:tx_inputs:Available inputs : [<ucoinpy.documents.transaction.InputSource object at 0x10ef8a898>, <ucoinpy.documents.transaction.InputSource object at 0x110f38ef0>]
DEBUG:wallet:send_money:Inputs : [<ucoinpy.documents.transaction.InputSource object at 0x10ef8a898>]
DEBUG:wallet:tx_outputs:<ucoinpy.documents.transaction.InputSource object at 0x10ef8a898>
DEBUG:wallet:send_money:Outputs : [<ucoinpy.documents.transaction.OutputSource object at 0x152a6dc88>, <ucoinpy.documents.transaction.OutputSource object at 0x152a6df60>]
DEBUG:wallet:send_money:TX : Version: 1
Type: Transaction
Currency: meta_brouzouf
Issuers:
7NoTJK95DYPDMpoad9obDPqXFW5JEXxmz4cyg39j5goQ
Inputs:
0:T:46407:96EB213B9089847DD1D5267D9DAC171986288732:2066583504791351
Outputs:
8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU:334981268413993
7NoTJK95DYPDMpoad9obDPqXFW5JEXxmz4cyg39j5goQ:1731602236377358
Comment: crash test  

DEBUG:document:sign:Signature : 
lx+LnufvNJWatbpJwU6pU+cj7meMZ+DTRx+JzZJgaPQe22NJJQQFmEnJx9stMGu1PXnIXZ03mum/33yKV/HNBw==
DEBUG:wallet:send_money:Transaction : Version: 1
Type: Transaction
Currency: meta_brouzouf
Issuers:
7NoTJK95DYPDMpoad9obDPqXFW5JEXxmz4cyg39j5goQ
Inputs:
0:T:46407:96EB213B9089847DD1D5267D9DAC171986288732:2066583504791351
Outputs:
8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU:334981268413993
7NoTJK95DYPDMpoad9obDPqXFW5JEXxmz4cyg39j5goQ:1731602236377358
Comment: crash test  
lx+LnufvNJWatbpJwU6pU+cj7meMZ+DTRx+JzZJgaPQe22NJJQQFmEnJx9stMGu1PXnIXZ03mum/33yKV/HNBw==

DEBUG:access:broadcast:Trying to connect to : HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk
DEBUG:__init__:post:do some work with
DEBUG:__init__:post:and send back
DEBUG:__init__:requests_post:POST : {'transaction': 'Version: 1\nType: Transaction\nCurrency: meta_brouzouf\nIssuers:\n7NoTJK95DYPDMpoad9obDPqXFW5JEXxmz4cyg39j5goQ\nInputs:\n0:T:46407:96EB213B9089847DD1D5267D9DAC171986288732:2066583504791351\nOutputs:\n8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU:334981268413993\n7NoTJK95DYPDMpoad9obDPqXFW5JEXxmz4cyg39j5goQ:1731602236377358\nComment: crash test  \nlx+LnufvNJWatbpJwU6pU+cj7meMZ+DTRx+JzZJgaPQe22NJJQQFmEnJx9stMGu1PXnIXZ03mum/33yKV/HNBw==\n'}
DEBUG:wallet:send_money:Key : *****key***** : ***********************
DEBUG:wallet:send_money:Sender pubkey:7NoTJK95DYPDMpoad9obDPqXFW5JEXxmz4cyg39j5goQ
DEBUG:wallet:tx_inputs:Available inputs : []
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Exception in callback Task._wakeup(<Future finis...*****************'>)
handle: <Handle Task._wakeup(<Future finis...be16AvocadoS'>)>
Traceback (most recent call last):
  File "/Users/travis/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/asyncio/events.py", line 120, in _run
  File "/Users/travis/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 292, in _wakeup
  File "/Users/travis/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 282, in _step
KeyError: <QEventLoop running=True closed=False debug=False>
```

**Comment by Insoleet** [comment]
It's missing last line.

**Comment by Samsemilio** [comment]
ops, sorry:
KeyError: <QEventLoop running=True closed=False debug=False>

**Comment by Insoleet** [comment]
Sakia 0.11.3 ?

**Comment by Samsemilio** [comment]
Oui

**Comment by Insoleet** [comment]
Interesting bug. It must come from modal windows having a different behaviour on macos... Or maybe something else, i'm not sure.

I don't have a mac so we will need an external contribution to fix this bug.

**Comment by Insoleet** [comment]
@Samsemilio : Can you try to reproduce this bug and precise exactly where you are clicking ?

**Comment by Samsemilio** [comment]
The same bug happens sometimes, the you are trying to certify someone. When you click twice the button or the same happens when you press enter. 
I think i discovered a pattern, when the sending or certification process is still "loading" and you click (or press enter) a second time, because of impassion, it crashes.

**Comment by Insoleet** [comment]
Does this still happen with 0.11.5 ?
