### ISSUE TITLE
Switching to UD mode make Sakia crash

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#404]
I was with quantitative units on transactions view, and then wanted to switch to UD mode:

```
DEBUG:__init__:_add_callback:Adding callback <Handle once_at
pper.<locals>.task_done(<Task finishe...s, not str',)>) at s
s.py:17> with delay 0
Traceback (most recent call last):
  File "sakia\models\txhistory.py", line 356, in headerData
  File "sakia\core\account.py", line 288, in current_ref
TypeError: tuple indices must be integers or slices, not str
```

**Comment by Insoleet** [comment]
Should be fixed in next release.
