### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#408]
Since this morning, Sakia starts and stop right after displaying tiles.

Traceback:

```
Task exception was never retrieved
future: <Task finished coro=<Node.connect_peers() done, defined at sakia\core\net\node.py:544> exception=TypeError("requests_get() missing 1 required positional argument: 'path'",)>
Traceback (most recent call last):
  File "sakia\core\net\node.py", line 554, in connect_peers
  File "site-packages\aiohttp\client.py", line 538, in __aenter__
  File "site-packages\aiohttp\client.py", line 295, in _ws_connect
aiohttp.errors.WSServerHandshakeError: 502, message='Invalid response status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio\tasks.py", line 239, in _step
  File "sakia\core\net\node.py", line 568, in connect_peers
  File "sakia\core\net\node.py", line 587, in request_peers
  File "site-packages\ucoinpy\api\bma\network\peering.py", line 87, in __get__
TypeError: requests_get() missing 1 required positional argument: 'path'
```

**Comment by Insoleet** [comment]
Yes, same problem here. I know the bug, won't be difficult to fix :)

**Comment by Insoleet** [comment]
Is it fixed in latest release ?

**Comment by c-geek** [comment]
Well I don't if it's the same bug or not, but here is the new stacktrace:

```
Task exception was never retrieved
future: <Task finished coro=<TxHistory._rollback() done, defined at sakia/core/txhistory.py:338> exception=AttributeError("'NoneType' object has no attribute 'blockUID'",)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/core/txhistory.py", line 358, in _rollback
  File "sakia/core/txhistory.py", line 333, in _check_block
AttributeError: 'NoneType' object has no attribute 'blockUID'
```

**Comment by c-geek** [comment]
(I have no network peer that I can reach)

**Comment by Insoleet** [comment]
Is this bug gone ?

**Comment by c-geek** [comment]
It seems, yes.

**Comment by Insoleet** [comment]
I added some checks, it should be ok.
