### ISSUE TITLE
Sakia close itself on RunTimeError Exception

### ISSUE THREAD

**Issue by vtexier** [duniter/sakia#412]
Sakia close itself, after trying to add a node with a connection error.
Version tag 0.20.0dev6.
```
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<Node.connect_current_block() done, defined at /home/vit/Documents/dev/python/sakia/src/sakia/core/net/node.py:345> exception=RuntimeError('Session is closed',)>
Traceback (most recent call last):
  File "/home/vit/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/vit/Documents/dev/python/sakia/src/sakia/core/net/node.py", line 355, in connect_current_block
    async with ws_connection as ws:
  File "/home/vit/.pyenv/versions/sakia-env/lib/python3.5/site-packages/aiohttp/client.py", line 538, in __aenter__
    self._resp = yield from self._coro
  File "/home/vit/.pyenv/versions/sakia-env/lib/python3.5/site-packages/aiohttp/client.py", line 287, in _ws_connect
    auth=auth)
  File "/home/vit/.pyenv/versions/sakia-env/lib/python3.5/site-packages/aiohttp/client.py", line 528, in __iter__
    resp = yield from self._coro
  File "/home/vit/.pyenv/versions/sakia-env/lib/python3.5/site-packages/aiohttp/client.py", line 150, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
```

**Comment by Insoleet** [comment]
Fixed
