### ISSUE TITLE
pyinstaller build error

### ISSUE THREAD

**Issue by vtexier** [duniter/sakia#420]
I get an import error when trying to build version 0.20.dev7 with pyinstaller on ubuntu 14.04 32bits.
Is there a new dependency to install for Qt 5 ?

```
Traceback (most recent call last):
  File "/home/vit/.pyenv/versions/sakia-env/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.1.1', 'console_scripts', 'pyinstaller')()
  File "/home/vit/.pyenv/versions/3.5.0/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/vit/.pyenv/versions/3.5.0/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/vit/.pyenv/versions/3.5.0/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/vit/.pyenv/versions/3.5.0/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 21, in <module>
  File "/home/vit/.pyenv/versions/3.5.0/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/home/vit/.pyenv/versions/3.5.0/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 183, in __postinit__
    self.assemble()
  File "/home/vit/.pyenv/versions/3.5.0/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 432, in assemble
    imphook_object = ImportHook(imported_name, hook_file)
  File "/home/vit/.pyenv/versions/3.5.0/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/imphook.py", line 182, in __init__
    self._module = importlib_load_source(hook_modname, self._filename)
  File "/home/vit/.pyenv/versions/3.5.0/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/compat.py", line 490, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vit/Documents/dev/python/sakia/hooks/hook-PyQt5.QtGui.py", line 13, in <module>
    from PyInstaller.utils.hooks import qt_plugins_binaries
ImportError: cannot import name 'qt_plugins_binaries'
```

**Comment by vtexier** [comment]
Pyinstaller upgraded to version 3.2 resolve the issue.
