### ISSUE TITLE
Crash to non-converted port

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#440]
At lauching this morning:
```fish
DEBUG:mainwindow:refresh:Refresh started
DEBUG:mainwindow:refresh:{'lang': 'fr_FR', 'account': 'moul', 'ref': 1, 'notifications': True, 'proxy_type': 'HTTP', 'international_system_of_units': True, 'digits_after_comma': 2, 'enable_proxy': False, 'proxy_port': 8080, 'maximized': False, 'expert_mode': True, 'proxy_address': '', 'forgetfulness': False, 'auto_refresh': False}
DEBUG:node:connect_current_block:Websocket block ValueError : Port number could not be converted. - 6bNSy
DEBUG:api:requests_get:Request : http://fe80::979:545a:a689:3b67:41673/blockchain/current
DEBUG:node:request_current_block:Port number could not be converted. : 6bNSy
DEBUG:node:connect_peers:Websocket peer ValueError : Port number could not be converted. - 6bNSy
DEBUG:api:requests_get:Request : http://fe80::979:545a:a689:3b67:41673/network/peering/peers
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<Node.connect_peers() done, defined at sakia/core/net/node.py:547> exception=ValueError('Port number could not be converted.',)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/core/net/node.py", line 571, in connect_peers
  File "sakia/core/net/node.py", line 590, in request_peers
  File "duniterpy/api/bma/network/peering.py", line 87, in __get__
  File "duniterpy/api/bma/api.py", line 165, in requests_get
  File "aiohttp/client.py", line 534, in __await__
  File "aiohttp/client.py", line 181, in _request
  File "aiohttp/client_reqrep.py", line 86, in __init__
  File "aiohttp/client_reqrep.py", line 116, in update_host
ValueError: Port number could not be converted.
LOADER: Back to parent (RC: 1)
LOADER: Doing cleanup
LOADER: Freeing archive status for /home/moul/projects/sakia/dist/sakia/sakia
```

**Comment by M5oul** [comment]
It works with removing the cache.
This bug is may be due to the lack of free memory on my memory hardware support.

**Comment by Insoleet** [comment]
It's probably a regex problem because ipv6 addresses are using double dots : 
```
fe80::979:545a:a689:3b67:41673
```
