### ISSUE TITLE
Debian Sid requires pip3 to install requirements, pip doesn't work

### ISSUE THREAD

**Issue by mmuman** [duniter/sakia#443]
When trying to run `pip install --upgrade -r requirements.txt` on Debian Sid, I get:
```
$ pip install --upgrade -r requirements.txt
Collecting git+https://github.com/harvimt/quamash.git@gh45 (from -r requirements.txt (line 2))
  Cloning https://github.com/harvimt/quamash.git (to gh45) to /tmp/pip-spkz6Z-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-spkz6Z-build/setup.py", line 2, in <module>
        import quamash
      File "quamash/__init__.py", line 1
    SyntaxError: Non-ASCII character '\xc2' in file quamash/__init__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-spkz6Z-build/
```
However using pip3 seems to work fine.

**Comment by Insoleet** [comment]
Were you with pyenv activated ?

**Comment by mmuman** [comment]
Hmm no.

**Comment by Insoleet** [comment]
You need to use pyenv to use Sakia dev ;)

**Comment by mmuman** [comment]
Why, oh why... :P
