### ISSUE TITLE
Crash on dev12

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#446]
Crash on dev12:
```fish
DEBUG:app:load:Loading data...
DEBUG:app:switch_language:Loading translations
DEBUG:app:switch_language:Loaded i18n/fr_FR
Traceback (most recent call last):
  File "ucoinpy/documents/document.py", line 35, in parse_field
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 70, in <module>
  File "src/sakia/core/app.py", line 88, in startup
  File "src/sakia/core/app.py", line 139, in get_account
  File "src/sakia/core/app.py", line 252, in load_account
  File "src/sakia/core/account.py", line 125, in load
  File "src/sakia/core/community.py", line 68, in load
  File "src/sakia/core/net/network.py", line 101, in from_json
  File "src/sakia/core/net/node.py", line 179, in from_json
  File "ucoinpy/documents/peer.py", line 63, in from_signed_raw
  File "ucoinpy/documents/document.py", line 37, in parse_field
ucoinpy.documents.document.MalformedDocumentError: Could not parse field Block
main returned -1
```

**Comment by Insoleet** [comment]
Can you copy your cache here ?

**Comment by M5oul** [comment]
Ok. It's fixed.

I have an other bug the window appear then:
```fish
DEBUG:community_view:refresh_quality_buttons:UID not published
DEBUG:wot_tab:draw_graph:Draw graph - moul
DEBUG:identity:is_member:Error : No peer answered in  community (0 peers available)
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<refresh_balance() done, defined at sakia/gui/transactions_tab.py:149> exception=NoPeerAvailable('', 0)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/transactions_tab.py", line 156, in refresh_balance
  File "sakia/core/money/relative_to_past.py", line 75, in localized
  File "sakia/core/community.py", line 305, in get_block
  File "sakia/core/net/api/bma/access.py", line 250, in future_request
sakia.tools.exceptions.NoPeerAvailable: Error : No peer answered in  community (0 peers available)
LOADER: Back to parent (RC: 1)
LOADER: Doing cleanup
LOADER: Freeing archive status for /home/moul/projects/sakia/dev12/sakia/sakia
```
It occur one time. Not the second time.

**Comment by Insoleet** [comment]
Thanks for the report. the first bug was really weird, because it happened when you loaded your cache.

I fixed the second issue... Do you have any details for the first issue ?

**Comment by M5oul** [comment]
Nope.
