### ISSUE TITLE
Sakia crashes when using captive portal Wifi

### ISSUE THREAD

**Issue by mmuman** [duniter/sakia#447]
When connecting to a wifi using a captive portal, the API requests get text/html data instead of JSON...
```
DEBUG:community:get_block:Requesting block 11192
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/network/peering
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/wot/lookup/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/node/summary
DEBUG:node:connect_peers:Websocket peer WSServerHandshakeError : 200, message='Invalid response status' - 8Fi1V
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/network/peering/peers
DEBUG:node:connect_current_block:Websocket block WSServerHandshakeError : 200, message='Invalid response status' - 8Fi1V
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/blockchain/current
WARNING:client_reqrep:json:Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
DEBUG:node:refresh_summary:JSONDecodeError : 8Fi1V
DEBUG:network_tab:refresh_nodes:Refresh nodes
DEBUG:community_view:refresh_status:Refresh status
DEBUG:community:get_block:Requesting block 11192
WARNING:client_reqrep:json:Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
DEBUG:node:refresh_informations:JSONDecodeError : 8Fi1V
WARNING:client_reqrep:json:Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
DEBUG:node:refresh_uid:JSONDecodeError : 8Fi1V
WARNING:client_reqrep:json:Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<Node.connect_peers() done, defined at sakia/core/net/node.py:547> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/core/net/node.py", line 571, in connect_peers
  File "sakia/core/net/node.py", line 590, in request_peers
  File "duniterpy/api/bma/network/peering.py", line 88, in __get__
  File "duniterpy/api/bma/api.py", line 150, in parse_response
  File "aiohttp/client_reqrep.py", line 761, in json
  File "json/__init__.py", line 319, in loads
  File "json/decoder.py", line 339, in decode
  File "json/decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
LOADER: Back to parent (RC: 1)
LOADER: Doing cleanup
LOADER: Freeing archive status for /home/revol/Téléchargements/dist/sakia/sakia
```

**Comment by Insoleet** [comment]
It was a bug in duniter-python-api, fixed in commit https://github.com/duniter/duniter-python-api/commit/72fc1e9943c1dcb7813c67d85dfc73c9995c5ead
