### ISSUE TITLE
Crash lorsque non membre d'une communauté

### ISSUE THREAD

**Issue by myckeul** [duniter/sakia#455]
Avec la dernière version stable 0.20.0 si j'essaye d'accéder à une communauté dont je ne suis pas membre sakia crash subittement.

Mon OS : Ubuntu 16.04 LTS

La version dev12 que j'avais précédemment fonctionnait, mais j'ai touché à la config de mon duniter entre temps, donc c'est peut-être d'un autre côté que ça pose problème.

Voici le débug : 

```
/opt/sakia/sakia/gui/community_view.py:296: RuntimeWarning: coroutine 'Community.get_block' was never awaited
DEBUG:wot_tab:draw_graph:Draw graph - myckeul
DEBUG:explorer_graph:_explore:search myckeul in 
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<refresh_quality_buttons() done, defined at sakia/gui/community_view.py:274> exception=AttributeError("'QPushButton' object has no attribute 'setEnable'",)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/community_view.py", line 297, in refresh_quality_buttons
AttributeError: 'QPushButton' object has no attribute 'setEnable'
LOADER: Back to parent (RC: 1)
LOADER: Doing cleanup
LOADER: Freeing archive status for /opt/sakia/sakia

```

**Comment by Insoleet** [comment]
C'est corrigé, je publie une release hotfix pour débloquer les utilisateurs non membres.
