### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#462]
The [binary build fail](https://github.com/duniter/sakia/wiki/Sakia-install-for-developpers#build-sakia-as-a-binary):
```fish
ta.so.54', 'BINARY'), ('libicui18n.so.54', '/lib64/libicui18n.so.54', 'BINARY'), ('libicuuc.so.54', '/lib64/libicuuc.so.54', 'BINARY'), ('libsodium.so', None, 'BINARY')]
99 INFO: checking PYZ
109 INFO: checking PKG
109 INFO: Bootloader /home/moul/.pyenv/versions/3.5.1/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/bootloader/Linux-64bit/run_d
109 INFO: checking EXE
110 WARNING: ignoring icon, platform not capable
110 INFO: checking COLLECT
110 INFO: Building COLLECT because out00-COLLECT.toc is non existent
WARNING: The output directory "/home/moul/projects/sakia_dev/dist/sakia" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
4909 INFO: Removing dir /home/moul/projects/sakia_dev/dist/sakia
4936 INFO: Building COLLECT out00-COLLECT.toc
Traceback (most recent call last):
  File "/home/moul/.pyenv/versions/sakia-env/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.2', 'console_scripts', 'pyinstaller')()
  File "/home/moul/.pyenv/versions/3.5.1/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/moul/.pyenv/versions/3.5.1/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/moul/.pyenv/versions/3.5.1/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/moul/.pyenv/versions/3.5.1/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 66, in <module>
  File "/home/moul/.pyenv/versions/3.5.1/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/api.py", line 642, in __init__
    self.__postinit__()
  File "/home/moul/.pyenv/versions/3.5.1/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/home/moul/.pyenv/versions/3.5.1/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/building/api.py", line 661, in assemble
    if not os.path.exists(fnm) or not os.path.isfile(fnm) and is_path_to_egg(fnm):
  File "/home/moul/.pyenv/versions/3.5.1/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: can't specify None for path argument
```

**Comment by M5oul** [comment]
I don't encounter it.
