### ISSUE TITLE
Issue while certifying

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#494]
I wanted to certify AnthonyLefevre, clicked on the "certify button", typed my password and then a popup showed up:

```

    Task exception was never retrieved
future: <Task finished coro=<accept() done, defined at sakia\gui\certification.py:109> exception=LookupFailureError('9Lr5b6J2QT6vR56RDyeUicE2ee3cQKPNvGrVcYEw1fTx', <sakia.core.community.Community object at 0x0000000004A45CA8>)>

    ----
    Traceback (most recent call last):

  File "sakia\core\registry\identity.py", line 119, in selfcert

  File "sakia\core\net\api\bma\access.py", line 241, in future_request

  File "site-packages\duniterpy\api\bma\wot.py", line 169, in __get__

  File "site-packages\duniterpy\api\bma\api.py", line 169, in requests_get

duniterpy.api.errors.DuniterError: Error code 2001 - No matching identity


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "asyncio\tasks.py", line 239, in _step

  File "sakia\gui\certification.py", line 121, in accept

  File "sakia\core\account.py", line 513, in certify

  File "sakia\core\registry\identity.py", line 147, in selfcert

sakia.tools.exceptions.LookupFailureError: Error : Person looked by 9Lr5b6J2QT6vR56RDyeUicE2ee3cQKPNvGrVcYEw1fTx in <sakia.core.community.Community object at 0x0000000004A45CA8> not found 


```

Note: once I closed the popup, I could click on the button again: this time I had no problem and the certification was sent successfully.

**Comment by Insoleet** [comment]
Well, probably that Sakia looked up 3 random nodes but no one knew about this identity. And next try, it randomly found a correct node... Do you imagine a better behaviour ?

**Comment by c-geek** [comment]
Yes, a better one would be to use the identity that is presented to me when I made the research. Sakia already have the data at that time.

**Comment by Insoleet** [comment]
Yes but Sakia does not cache the lookup requests because they can change from one node to another.

But all these things should change, the Data Access layer needs a lot of enhancements.
