### ISSUE TITLE
Can't test feature/agent_architecture branch

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#496]
I am trying `feature/agent_architecture` branch.
What did I missed?
```fish
/home/moul/projects/sakia_dev/res/ui/search_user_view.ui >> /home/moul/projects/sakia_dev/src/sakia/presentation/search_user_view_uic.py
/home/moul/projects/sakia_dev/res/icons/icons.qrc >> /home/moul/projects/sakia_dev/src/icons_rc.py
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/node_manager_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/contact_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/account_cfg_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/certifications_tab_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/explorer_tab_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/import_account_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/member_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/community_cfg_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/create_wallet_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/about_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/community_view_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/currency_tab_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/toast_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/preferences_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/wallets_tab_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/transfer_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/certification_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/search_user_view_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/revocation_uic.py"
Error: No such file or directory: "/home/moul/projects/sakia_dev/src/sakia/presentation/password_asker_uic.py"
/home/moul/projects/sakia_dev/res/i18n/ts/fr_FR.ts
/home/moul/projects/sakia_dev/res/i18n/ts/pt_BR.ts
/home/moul/projects/sakia_dev/res/i18n/ts/es_ES.ts
/home/moul/projects/sakia_dev/res/i18n/ts/de_DE.ts
/home/moul/projects/sakia_dev/res/i18n/ts/pl_PL.ts
/home/moul/projects/sakia_dev/res/i18n/ts/it_IT.ts
/home/moul/projects/sakia_dev/res/i18n/ts/ru_RU.ts
Updating '/home/moul/projects/sakia_dev/res/i18n/qm/fr_FR.qm'...
    Generated 347 translation(s) (323 finished and 24 unfinished)
    Ignored 50 untranslated source text(s)
/home/moul/projects/sakia_dev/res/i18n/ts/fr_FR.ts >> /home/moul/projects/sakia_dev/res/i18n/qm/fr_FR.qm
Updating '/home/moul/projects/sakia_dev/res/i18n/qm/pt_BR.qm'...
    Generated 269 translation(s) (198 finished and 71 unfinished)
    Ignored 128 untranslated source text(s)
/home/moul/projects/sakia_dev/res/i18n/ts/pt_BR.ts >> /home/moul/projects/sakia_dev/res/i18n/qm/pt_BR.qm
Updating '/home/moul/projects/sakia_dev/res/i18n/qm/es_ES.qm'...
    Generated 271 translation(s) (192 finished and 79 unfinished)
    Ignored 126 untranslated source text(s)
/home/moul/projects/sakia_dev/res/i18n/ts/es_ES.ts >> /home/moul/projects/sakia_dev/res/i18n/qm/es_ES.qm
Updating '/home/moul/projects/sakia_dev/res/i18n/qm/de_DE.qm'...
    Generated 272 translation(s) (187 finished and 85 unfinished)
    Ignored 125 untranslated source text(s)
/home/moul/projects/sakia_dev/res/i18n/ts/de_DE.ts >> /home/moul/projects/sakia_dev/res/i18n/qm/de_DE.qm
Updating '/home/moul/projects/sakia_dev/res/i18n/qm/pl_PL.qm'...
    Generated 227 translation(s) (139 finished and 88 unfinished)
    Ignored 170 untranslated source text(s)
/home/moul/projects/sakia_dev/res/i18n/ts/pl_PL.ts >> /home/moul/projects/sakia_dev/res/i18n/qm/pl_PL.qm
Updating '/home/moul/projects/sakia_dev/res/i18n/qm/it_IT.qm'...
    Generated 275 translation(s) (208 finished and 67 unfinished)
    Ignored 122 untranslated source text(s)
/home/moul/projects/sakia_dev/res/i18n/ts/it_IT.ts >> /home/moul/projects/sakia_dev/res/i18n/qm/it_IT.qm
Updating '/home/moul/projects/sakia_dev/res/i18n/qm/ru_RU.qm'...
    Generated 150 translation(s) (84 finished and 66 unfinished)
    Ignored 247 untranslated source text(s)
/home/moul/projects/sakia_dev/res/i18n/ts/ru_RU.ts >> /home/moul/projects/sakia_dev/res/i18n/qm/ru_RU.qm
<RCC>
      <qresource prefix="i18n">
<file alias="fr_FR">qm/fr_FR.qm</file>
<file alias="pt_BR">qm/pt_BR.qm</file>
<file alias="es_ES">qm/es_ES.qm</file>
<file alias="de_DE">qm/de_DE.qm</file>
<file alias="pl_PL">qm/pl_PL.qm</file>
<file alias="it_IT">qm/it_IT.qm</file>
<file alias="ru_RU">qm/ru_RU.qm</file>
      </qresource>
    </RCC>
    
/home/moul/projects/sakia_dev/res/i18n/langs-1470652395.qrc >> /home/moul/projects/sakia_dev/src/i18n_rc.py
Traceback (most recent call last):
  File "src/sakia/main.py", line 23, in <module>
    from sakia.gui.main_window.controller import MainWindowController
  File "/home/moul/projects/sakia_dev/src/sakia/gui/main_window/controller.py", line 14, in <module>
    from ..password_asker import PasswordAskerDialog
  File "/home/moul/projects/sakia_dev/src/sakia/gui/password_asker.py", line 13, in <module>
    from ..presentation.password_asker_uic import Ui_PasswordAskerDialog
ImportError: No module named 'sakia.presentation'
```

**Comment by Insoleet** [comment]
This branch won't work for a while. Please remain on the dev branch until I finished the refactoring ;)

**Comment by M5oul** [comment]
Ok, no problem.
