### ISSUE TITLE
Error when certifying pegase38

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#498]
```bash
DEBUG:account:certify:Certdata
DEBUG:api:requests_get:Request : http://duniter.fraslin.net:8999/wot/lookup/2KGkiN6cuz9KTSYvDFw5nWR1PYSUu7RWs3Xj3kxJnB1F
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<accept() done, defined at /home/moul/projects/sakia_dev/src/sakia/gui/certification.py:109> exception=LookupFailureError('2KGkiN6cuz9KTSYvDFw5nWR1PYSUu7RWs3Xj3kxJnB1F', <sakia.core.community.Community object at 0x7f8b94684168>)>
Traceback (most recent call last):
  File "/home/moul/projects/sakia_dev/src/sakia/core/registry/identity.py", line 119, in selfcert
    req_args={'search': self.pubkey})
  File "/home/moul/projects/sakia_dev/src/sakia/core/net/api/bma/access.py", line 241, in future_request
    json_data = await req.get(**get_args, session=self._network.session)
  File "/home/moul/.pyenv/versions/sakia-env/lib/python3.5/site-packages/duniterpy/api/bma/wot.py", line 169, in __get__
    r = await self.requests_get(session, '/lookup/%s' % self.search, **kwargs)
  File "/home/moul/.pyenv/versions/sakia-env/lib/python3.5/site-packages/duniterpy/api/bma/api.py", line 169, in requests_get
    raise DuniterError(error_data)
duniterpy.api.errors.DuniterError: Error code 2001 - No matching identity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/moul/.pyenv/versions/3.5.1/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/moul/projects/sakia_dev/src/sakia/gui/certification.py", line 121, in accept
    result = await self.account.certify(password, self.community, pubkey)
  File "/home/moul/projects/sakia_dev/src/sakia/core/account.py", line 513, in certify
    selfcert = await identity.selfcert(community)
  File "/home/moul/projects/sakia_dev/src/sakia/core/registry/identity.py", line 147, in selfcert
    raise LookupFailureError(self.pubkey, community)
sakia.tools.exceptions.LookupFailureError: Error : Person looked by 2KGkiN6cuz9KTSYvDFw5nWR1PYSUu7RWs3Xj3kxJnB1F in <sakia.core.community.Community object at 0x7f8b94684168> not found 
DEBUG:node:connect_current_block:Websocket block WSServerHandshakeError : 502, message='Invalid response status' - 8Fi1V
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/blockchain/current
```

**Comment by M5oul** [comment]
Jean_F get `The certification's sandbox is full. Please retry with another document or retry later` with Cesium.

**Comment by M5oul** [comment]
This bug happen when I had a bad connection.
Now, I have a better connection, and everything went well: I could certify him.
