### ISSUE TITLE
Warning_revokation

### ISSUE THREAD

**Issue by urodelus** [duniter/sakia#500]
```
    Task exception was never retrieved
future: <Task finished coro=<refresh_status() done, defined at sakia\gui\community_view.py:270> exception=KeyError('warning_revokation',)>
    ----
    Traceback (most recent call last):
  File "asyncio\tasks.py", line 239, in _step
  File "sakia\gui\community_view.py", line 312, in refresh_status
  File "sakia\gui\community_view.py", line 312, in <listcomp>
KeyError: 'warning_revokation'
```

This warning appears using sakia-0.20.6-win64.exe

**Comment by M5oul** [comment]
Nice you catch it.
I also get the notification.

**Comment by M5oul** [comment]
I reproduce it, I don't have same error logs:
```bash
DEBUG:txhistory:refresh:Starts a new refresh
DEBUG:txhistory:_refresh:Refresh from : 30041 to 30047
DEBUG:api:requests_get:Request : http://duniter.moul.re:8999/ud/history/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:community:get_block:Requesting block 25596
DEBUG:toast:display:NOTIFY DISPLAY
DEBUG:api:requests_get:Request : http://duniter.help-web-low.fr:8999/wot/certifiers-of/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:api:requests_get:Request : http://mirror2.cgeek.fr:9332/blockchain/with/tx
DEBUG:api:requests_get:Request : http://duniter.moul.re:8999/wot/lookup/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:api:requests_get:Request : http://duniter.moul.re:8999/tx/sources/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:community_view:refresh_status:Refresh status
DEBUG:community:get_block:Requesting block 30047
DEBUG:community_view:refresh_quality_buttons:UID Published
DEBUG:api:requests_get:Request : http://test-net.duniter.fr:9201/blockchain/with/ud
DEBUG:account:wallet_finished:Finished loading wallet
```
It only see the `NOTIFY DISPLAX`.
