### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by vincentux** [duniter/sakia#506]
je penses que ça vient du fait que les nœuds soient passés en V0.30, ou pas ... ?!
enfin voila le 1er message 
```
Task exception was never retrieved
future: <Task finished coro=<TxHistory._refresh() done, defined at sakia/core/txhistory.py:245> exception=MalformedDocumentError('Could not parse field Issuer',)>
Traceback (most recent call last):
File "site-packages/duniterpy/documents/document.py", line 36, in parse_field
AttributeError: 'NoneType' object has no attribute 'group'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "asyncio/tasks.py", line 239, in _step
File "sakia/core/txhistory.py", line 288, in _refresh
File "site-packages/duniterpy/documents/block.py", line 258, in from_signed_raw
File "site-packages/duniterpy/documents/document.py", line 38, in parse_field
duniterpy.documents.document.MalformedDocumentError: Could not parse field Issuer
```
et le deuxième
```
Exception in callback Task._wakeup(<Future finished result=None>)
handle: <Handle Task._wakeup(<Future finished result=None>)>
Traceback (most recent call last):
File "asyncio/events.py", line 125, in _run
File "asyncio/tasks.py", line 307, in _wakeup
File "asyncio/tasks.py", line 291, in _step
KeyError: <QSelectorEventLoop running=True closed=False debug=False> 
```

**Comment by Insoleet** [comment]
Duplicate of #507
