### ISSUE TITLE
Segfault with Qt 5.7.0

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#512]
I don't know if it come from the fact I am using Fedora package.
It seems [Qt 5.7.0](https://apps.fedoraproject.org/packages/qt5) is installed.
I report it, it could be usefull:

``` sh
DEBUG:node:connect_peers:Received a peer : BSmby
DEBUG:node:connect_peers:Received a peer : BSmby
DEBUG:node:connect_peers:Received a peer : HnFcS
DEBUG:node:connect_peers:Received a peer : BSmby
QObject::connect: Cannot queue arguments of type 'QTextBlock'
(Make sure 'QTextBlock' is registered using qRegisterMetaType().)
./run_sakia.sh : ligne 9 : 10057 Segmentation fault      (core dumped)python3 src/sakia/main.py -d
```

**Comment by M5oul** [comment]
More logs or an other issue:
```sh
DEBUG:network_tab:refresh_nodes:Refresh nodes
DEBUG:api:requests_get:Request : http://peer.duniter.org:8999/network/peering/peers
DEBUG:api:requests_get:Request : http://peer.duniter.org:8999/network/peering
DEBUG:main:async_exception_handler:Exception handler executing
DEBUG:api:requests_get:Request : http://peer.duniter.org:8999/wot/lookup/JAe4uc3gdbFxHfctDswp1F2CBTAe8peVVYNGgXSnsqNG
ERROR:main:async_exception_handler:Future exception was never retrieved
future: <Future finished exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/quamash/__init__.py", line 85, in run
    r = callback(*args, **kwargs)
  File "/usr/lib64/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 24] Too many open files
DEBUG:api:requests_get:Request : http://peer.duniter.org:8999/node/summary
QObject::setParent: Cannot set parent, new parent is in a different thread
DEBUG:community_view:refresh_status:Refresh status
DEBUG:community:get_block:Requesting block 32561
DEBUG:community_view:refresh_quality_buttons:UID Published
QObject::connect: Cannot queue arguments of type 'QTextBlock'
(Make sure 'QTextBlock' is registered using qRegisterMetaType().)
./run_sakia.sh : ligne 9 : 17408 Segmentation fault      (core dumped)python3 src/sakia/main.py -d
```

**Comment by Insoleet** [comment]
Interesting. Is it sakia you run by yourself ? 

With PyQt 5.7, it seems you can install it from pip and you don't need to built it by yourself. Can you do : 

`pip install --upgrade PyQt5` 

And tell me how it goes ?

**Comment by M5oul** [comment]
Yep, I am using Sakia on `dev` branch without `pyenv` and extra things.
I am using Python 3.5.1 and Qt from Fedora packages.
I installed `pip install --upgrade PyQt5`, It works fine.

**Comment by Insoleet** [comment]
So it's fixed ?

**Comment by M5oul** [comment]
I don't know, it did happen only once.
Seems a rare bug.

**Comment by M5oul** [comment]
Ok, finally, I reproduced it.
After restarted Sakia to make it run with this lib.
