### ISSUE TITLE
Critical error while sending money

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#516]
```
    Task exception was never retrieved
future: <Task finished coro=<accept() done, defined at sakia\gui\transfer.py:114> exception=ValueError('max() arg is an empty sequence',)>

    ----
    Traceback (most recent call last):

  File "asyncio\tasks.py", line 239, in _step

  File "sakia\gui\transfer.py", line 153, in accept

  File "sakia\core\wallet.py", line 364, in send_money

  File "sakia\core\wallet.py", line 295, in prepare_tx

  File "sakia\core\wallet.py", line 193, in tx_sources

ValueError: max() arg is an empty sequence
```

**Comment by Insoleet** [comment]
Sakia did not success in loading yoru sources. That's why you have an empty sequence. This probably happened because of a failure in refreshing your transactions.

Also, it looks like there are a lot of network errors and timeouts with latest sakia/duniter changes.
