### ISSUE TITLE
All nodes are red on network tab

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#520]
```bash
DEBUG:community:get_ud_block:Error : No peer answered in  community (0 peers available)
DEBUG:community:get_ud_block:Error : No peer answered in  community (0 peers available)
DEBUG:community:get_ud_block:Error : No peer answered in  community (0 peers available)
DEBUG:community:get_ud_block:Error : No peer answered in  community (0 peers available)
DEBUG:community:get_ud_block:Error : No peer answered in  community (0 peers available)
DEBUG:community:get_ud_block:Error : No peer answered in  community (0 peers available)
DEBUG:community:get_ud_block:Error : No peer answered in  community (0 peers available)
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<refresh_transfers() done, defined at /home/moul/projects/sakia_dev/src/sakia/gui/navigation/txhistory/table_model.py:304> exception=TypeError("'NoneType' object is not subscriptable",)>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 241, in _step
  File "/home/moul/projects/sakia_dev/src/sakia/gui/navigation/txhistory/table_model.py", line 330, in refresh_transfers
  File "/usr/lib64/python3.5/asyncio/futures.py", line 358, in __iter__
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 290, in _wakeup
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
  File "/home/moul/projects/sakia_dev/src/sakia/gui/navigation/txhistory/table_model.py", line 241, in data_received
  File "/home/moul/projects/sakia_dev/src/sakia/core/money/relative_to_past.py", line 111, in diff_localized
TypeError: 'NoneType' object is not subscriptable
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<refresh_transfers() done, defined at /home/moul/projects/sakia_dev/src/sakia/gui/navigation/txhistory/table_model.py:304> exception=TypeError("'NoneType' object is not subscriptable",)>
Traceback (most recent call last):
```

**Comment by Insoleet** [comment]
Yeah I saw it too. There are problems with Sakia scalability. That's why I'm planning on reworking everything instead of trying to fix this mess :)

**Comment by M5oul** [comment]
Yeah, sure :+1:

**Comment by Insoleet** [comment]
I'm pushing a fix for the exception in the stacktrace, not for the red network tab.
