### ISSUE TITLE
Logs error

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#521]
``` sh
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/blockchain/with/ud
ERROR:main:async_exception_handler:Future exception was never retrieved
future: <Future finished exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/quamash/__init__.py", line 85, in run
    r = callback(*args, **kwargs)
  File "/usr/lib64/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 24] Too many open files
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/blockchain/with/ud
QObject::setParent: Cannot set parent, new parent is in a different thread
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Future exception was never retrieved
future: <Future finished exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/quamash/__init__.py", line 85, in run
    r = callback(*args, **kwargs)
  File "/usr/lib64/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 24] Too many open files
QObject::setParent: Cannot set parent, new parent is in a different thread
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/blockchain/with/ud
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/blockchain/with/ud
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/blockchain/with/ud
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/blockchain/with/ud
DEBUG:api:requests_get:Request : http://testnet.duniter.inso.ovh:80/blockchain/with/ud
```

**Comment by Insoleet** [comment]
Was sakia opened for a long time ?

**Comment by M5oul** [comment]
Less than one hour.
