### ISSUE TITLE
Erreur passage de "non membre" a "membre" ?

### ISSUE THREAD

**Issue by vincentux** [duniter/sakia#559]
J'ouvre Sakia 0.30.0béta5 et je vois mon statut en "non membre" ensuite au moment du passage à "membre" (enfin je crois que ça viens de ça) j'ai eu une fenêtre d'erreur (je n'ai rien touché en tout cas).

   ```
 An unhandled exception occured
    ----
    Traceback (most recent call last):
  File "sakia/gui/navigation/graphs/wot/controller.py", line 55, in handle_identity_change
  File "sakia/gui/navigation/graphs/wot/model.py", line 49, in refresh
  File "sakia/data/graphs/wot_graph.py", line 52, in offline_init
  File "sakia/data/graphs/base_graph.py", line 172, in add_offline_certifier_list
  File "sakia/data/graphs/base_graph.py", line 69, in offline_node_status
AttributeError: 'NoneType' object has no attribute 'pubkey'
```

**Comment by vincentux** [comment]
et quand je clique sur ok, erreur (suite)
   ```
 Exception in callback Task._wakeup(<_GatheringFu...oi9pV5E73e'}]>)
handle: <Handle Task._wakeup(<_GatheringFu...oi9pV5E73e'}]>)>
    ----
    Traceback (most recent call last):
  File "asyncio/events.py", line 125, in _run
  File "asyncio/tasks.py", line 307, in _wakeup
  File "asyncio/tasks.py", line 291, in _step
KeyError: <QSelectorEventLoop running=True closed=False debug=False>
```

**Comment by vincentux** [comment]
Problème résolu :p 
`rm ~/.config/sakia/Default\ Profile/*.db`

Désolé ...

**Comment by Insoleet** [comment]
Il y avait un vrai bug qui sera corrigé dans la prochaine release :)
