### ISSUE TITLE
Errors on Sakia 0.30.0b5

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#566]
With test-net:
```bash
LOADER: Running main.py
ERROR:root:Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f414f025828>
ERROR:root:Exception in callback Task._wakeup(<Future finished result=None>)
handle: <Handle Task._wakeup(<Future finished result=None>)>
Traceback (most recent call last):
  File "asyncio/events.py", line 125, in _run
  File "asyncio/tasks.py", line 307, in _wakeup
  File "asyncio/tasks.py", line 291, in _step
KeyError: <QSelectorEventLoop running=False closed=False debug=False>
ERROR:root:Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f414f083898>
ERROR:root:Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f414f1e4940>
ERROR:root:Exception in callback Task._wakeup(<Future finished result=None>)
handle: <Handle Task._wakeup(<Future finished result=None>)>
Traceback (most recent call last):
  File "asyncio/events.py", line 125, in _run
  File "asyncio/tasks.py", line 307, in _wakeup
  File "asyncio/tasks.py", line 291, in _step
KeyError: <QSelectorEventLoop running=False closed=False debug=False>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio/events.py", line 125, in _run
  File "asyncio/tasks.py", line 307, in _wakeup
  File "asyncio/tasks.py", line 291, in _step
KeyError: <QSelectorEventLoop running=False closed=False debug=False>
ERROR:root:Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f414fe89c18>
```

**Comment by Insoleet** [comment]
Weird bug once again. I cannot reproduce it. Do you have more information ?

**Comment by M5oul** [comment]
nope.

**Comment by Insoleet** [comment]
Did you reproduce since then ?

**Comment by M5oul** [comment]
I didn't test test-net since it's no more important.
This ticket could be closed.
