### ISSUE TITLE
Erreur au demarrage de Sakia

### ISSUE THREAD

**Issue by vincentux** [duniter/sakia#572]
Je viens d'avoir cette erreur en redémarrant Sakia : 

```
sakia --currency gtest -d
PyInstaller Bootloader 3.x
LOADER: executable is /opt/sakia/sakia.bin
LOADER: homepath is /opt/sakia
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /opt/sakia/sakia.bin
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /opt/sakia
LOADER: LD_LIBRARY_PATH=/opt/sakia
PyInstaller Bootloader 3.x
LOADER: executable is /opt/sakia/sakia.bin
LOADER: homepath is /opt/sakia
LOADER: _MEIPASS2 is /opt/sakia
LOADER: archivename is /opt/sakia/sakia.bin
LOADER: Already in the child - running user's code.
LOADER: Python library: /opt/sakia/libpython3.5m.so.1.0
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is /opt/sakia/base_library.zip:/opt/sakia
LOADER: sys.prefix is /opt/sakia
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is /opt/sakia/base_library.zip:/opt/sakia
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_qt5.py
LOADER: Running pyi_rth_qt5plugins.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running main.py
DEBUG:meta:prepare:Initializing meta database
DEBUG:meta:upgrade_database:Begin upgrade of database...
DEBUG:meta:upgrade_database:End upgrade of database...
DEBUG:network:add_connector:4jT89 connected
DEBUG:network:add_connector:5ocqz connected
DEBUG:network:add_connector:BnSRj connected
DEBUG:network:add_connector:C4orq connected
DEBUG:network:add_connector:CFP3o connected
DEBUG:network:add_connector:CSjgc connected
DEBUG:network:add_connector:D3nN6 connected
DEBUG:network:add_connector:HnFcS connected
DEBUG:network:add_connector:J2Apo connected
DEBUG:controller:dates_changed:Changed dates
DEBUG:controller:dates_changed:Changed dates
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<draw_graph() done, defined at sakia/gui/navigation/graphs/wot/controller.py:58> exception=AttributeError("'NoneType' object has no attribute 'pubkey'",)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/navigation/graphs/wot/controller.py", line 67, in draw_graph
  File "sakia/gui/navigation/graphs/wot/model.py", line 43, in set_identity
  File "sakia/data/graphs/wot_graph.py", line 52, in offline_init
  File "sakia/data/graphs/base_graph.py", line 172, in add_offline_certifier_list
  File "sakia/data/graphs/base_graph.py", line 69, in offline_node_status
AttributeError: 'NoneType' object has no attribute 'pubkey'
DEBUG:node:connect_current_block:[Errno 22] Cannot connect to host fe80::b2c0:b69b:36e6:f895:60527 ssl:False [Can not connect to fe80::b2c0:b69b:36e6:f895:60527 [Argument invalide]] : BnSRj
DEBUG:node:connect_peers:[Errno 22] Cannot connect to host fe80::b2c0:b69b:36e6:f895:60527 ssl:False [Can not connect to fe80::b2c0:b69b:36e6:f895:60527 [Argument invalide]] : BnSRj
DEBUG:node:connect_peers:Could not connect to any BMA endpoint : BnSRj
DEBUG:node:connect_current_block:Connected successfully to block ws : D3nN6
DEBUG:node:connect_current_block:Received a block : D3nN6
DEBUG:node:connect_peers:Connected successfully to peer ws : D3nN6
DEBUG:node:connect_current_block:Connected successfully to block ws : CSjgc
DEBUG:node:connect_current_block:Connected successfully to block ws : 5ocqz
DEBUG:node:connect_current_block:Received a block : 5ocqz
DEBUG:node:connect_peers:Connected successfully to peer ws : CSjgc
DEBUG:node:connect_current_block:Received a block : CSjgc
DEBUG:node:connect_peers:Connected successfully to peer ws : 5ocqz
DEBUG:node:connect_current_block:Connected successfully to block ws : CFP3o
DEBUG:node:connect_peers:Connected successfully to peer ws : CFP3o
DEBUG:node:connect_current_block:Connected successfully to block ws : C4orq
DEBUG:node:connect_current_block:Received a block : C4orq
DEBUG:node:connect_current_block:Received a block : CFP3o
DEBUG:node:connect_peers:Connected successfully to peer ws : C4orq
DEBUG:node:connect_peers:Connected successfully to peer ws : J2Apo
DEBUG:node:connect_current_block:Connected successfully to block ws : J2Apo
DEBUG:node:connect_current_block:Received a block : J2Apo
DEBUG:node:connect_current_block:Connected successfully to block ws : HnFcS
DEBUG:node:connect_peers:Connected successfully to peer ws : HnFcS
DEBUG:node:connect_current_block:Received a block : HnFcS
DEBUG:node:connect_current_block:Connected successfully to block ws : 4jT89
DEBUG:node:connect_peers:Connected successfully to peer ws : 4jT89
DEBUG:node:connect_current_block:Received a block : 4jT89
DEBUG:node:connect_peers:Received a peer : CFP3o
DEBUG:network:handle_new_node:Stacking new peer document : CFP3oacjwDJARL89D2Gkz6LeMoVAu4ggE65CvqSp9Q9K
DEBUG:node:connect_peers:Received a peer : CFP3o
DEBUG:node:connect_peers:Received a peer : HnFcS
DEBUG:node:connect_peers:Received a peer : D3nN6
DEBUG:node:connect_peers:Received a peer : 5ocqz
DEBUG:node:connect_peers:Received a peer : 4jT89
DEBUG:node:connect_current_block:[Errno 22] Cannot connect to host fe80::b2c0:b69b:36e6:f895:60527 ssl:False [Can not connect to fe80::b2c0:b69b:36e6:f895:60527 [Argument invalide]] : BnSRj
DEBUG:node:connect_peers:[Errno 22] Cannot connect to host fe80::b2c0:b69b:36e6:f895:60527 ssl:False [Can not connect to fe80::b2c0:b69b:36e6:f895:60527 [Argument invalide]] : BnSRj
DEBUG:node:connect_peers:Could not connect to any BMA endpoint : BnSRj
DEBUG:node:connect_peers:Received a peer : J2Apo
DEBUG:node:connect_peers:Received a peer : C4orq
DEBUG:bma:verified_get:Requesting requirements on endpoint BASIC_MERKLED_API gtest.duniter.fr 88.189.14.141 10900
DEBUG:bma:verified_get:Requesting requirements on endpoint BASIC_MERKLED_API gtest.vincentux.fr 10.2.126.5 8999
DEBUG:bma:verified_get:Requesting requirements on endpoint BASIC_MERKLED_API 192.168.0.31 2a01:e35:2ef7:8ed0:190c:7d34:dec9:7b4a 8999
DEBUG:bma:verified_get:Requesting requirements on endpoint BASIC_MERKLED_API 88.190.82.70 51776
DEBUG:bma:verified_get:Requesting block on endpoint BASIC_MERKLED_API gtest.duniter.fr 88.189.14.141 10900
DEBUG:bma:verified_get:Requesting block on endpoint BASIC_MERKLED_API gtest.vincentux.fr 10.2.126.5 8999
DEBUG:bma:verified_get:Requesting block on endpoint BASIC_MERKLED_API 192.168.0.31 2a01:e35:2ef7:8ed0:190c:7d34:dec9:7b4a 8999
DEBUG:bma:verified_get:Requesting block on endpoint BASIC_MERKLED_API 88.190.82.70 51776 
```

**Comment by Insoleet** [comment]
Oui c'est une erreur que j'ai eu aussi, elle sera corrigée dans la prochaine release.
