### ISSUE TITLE
Error on Sakia 0.30.0b9

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#574]
```bash

    Task exception was never retrieved
future: <Task finished coro=<draw_graph() done, defined at sakia/gui/navigation/graphs/wot/controller.py:58> exception=AttributeError("'NoneType' object has no attribute 'pubkey'",)>

    ----
    Traceback (most recent call last):

  File "asyncio/tasks.py", line 239, in _step

  File "sakia/gui/navigation/graphs/wot/controller.py", line 67, in draw_graph

  File "sakia/gui/navigation/graphs/wot/model.py", line 43, in set_identity

  File "sakia/data/graphs/wot_graph.py", line 52, in offline_init

  File "sakia/data/graphs/base_graph.py", line 172, in add_offline_certifier_list

  File "sakia/data/graphs/base_graph.py", line 69, in offline_node_status

AttributeError: 'NoneType' object has no attribute 'pubkey'
```

**Comment by Insoleet** [comment]
Fixed since release 0.30.0.

**Comment by Pafzedog** [comment]
Salut,

je suis sur la version Linux  0.30.2 et j'obtiens la même erreur à chaque démarrage.

**Comment by M5oul** [comment]
I reopen as it don't seems corrected.
On my side, I didn't reproduced it.

**Comment by Pafzedog** [comment]
autant pour moi, j'avais bien supprimer le repertoire .config/sakia mais il restait des vieux fichiers de conf de l'époque ou j'avais installé sakia dans /opt avec le zip.
après suppression de toutes les occurences de fichiers 'sakia', tout semble rentré dans l'ordre :)
