### ISSUE TITLE
Sakia 0.30 bug

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#576]
While click on WoT window on ID : Caizohan (not member, so red rounded) : 

```bash
    Task exception was never retrieved
future: <Task finished coro=<draw_graph() done, defined at sakia/gui/navigation/graphs/wot/controller.py:58> exception=TypeError("unhashable type: 'list'",)>

    ----
    Traceback (most recent call last):

  File "asyncio/tasks.py", line 239, in _step

  File "sakia/gui/navigation/graphs/wot/controller.py", line 67, in draw_graph

  File "sakia/gui/navigation/graphs/wot/model.py", line 39, in set_identity

  File "sakia/data/graphs/wot_graph.py", line 21, in initialize

  File "sakia/data/graphs/base_graph.py", line 52, in node_status

  File "sakia/services/identities.py", line 374, in load_requirements

  File "sakia/data/connectors/bma.py", line 260, in get

  File "sakia/data/connectors/bma.py", line 224, in verified_get

  File "sakia/data/connectors/bma.py", line 151, in _best_answer

TypeError: unhashable type: 'list'
```

**Comment by Insoleet** [comment]
Fixed in 0.30.2.
