### ISSUE TITLE
Can't run 0.30.2

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#578]
```bash
LOADER: Running main.py
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "sakia/main.py", line 94, in <module>
  File "sakia/app.py", line 223, in connection_exists
  File "sakia/data/processors/connections.py", line 36, in connections
  File "sakia/data/repositories/connections.py", line 82, in get_all
  File "sakia/data/repositories/connections.py", line 82, in <listcomp>
TypeError: __init__() takes from 3 to 8 positional arguments but 9 were given
Failed to execute script main
LOADER: OK.
LOADER: Cleaning up Python interpreter.
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<get_last_version() running at sakia/app.py:185>>
sys:1: RuntimeWarning: coroutine 'get_last_version' was never awaited
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /home/moul/projects/sakia_build/dist/sakia/sakia.bin
```

**Comment by Insoleet** [comment]
You should remove your ~/.config/sakia, even if you used the beta version before.

**Comment by M5oul** [comment]
In fact.
Thanks, it works.
