### ISSUE TITLE
Error: Identity change

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#590]
Report:

	    An unhandled exception occured

	    ----
	    Traceback (most recent call last):

	  File "sakia/gui/navigation/graphs/wot/controller.py", line 56, in handle_identity_change

	  File "sakia/gui/navigation/graphs/wot/model.py", line 49, in refresh

	  File "sakia/data/graphs/wot_graph.py", line 55, in offline_init

	  File "sakia/data/graphs/base_graph.py", line 193, in add_offline_certified_list

	  File "sakia/data/graphs/base_graph.py", line 145, in add_certified_node

	AttributeError: 'NoneType' object has no attribute 'uid'

**Comment by Insoleet** [comment]
What did you do exactly ?

**Comment by c-geek** [comment]
I just started Sakia. It shows up Network tab, and I get this error.

**Comment by Insoleet** [comment]
Oh, ok. This was supposed to be fixed by https://github.com/duniter/sakia/commit/d920eb002af4659770d25b276eb96566df5e669b but it seems not. Can you share your database please so that I reproduce the error ?

**Comment by c-geek** [comment]
Yes: https://framadrop.org/r/Xazw4r_Rcx#csH5zvu4u60ePKlxuYONbYsI1pLQalCwQ6gc5JLnagE=

I will try to remember to give you all these details each time I make a new issue.

**Comment by Insoleet** [comment]
There was probably some connection issues loading an identity. I will ignore this error and log and error for the moment.
