### ISSUE TITLE
Sakia first launch error

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#592]
I've deleted my `~/.config/sakia` folder and relaunched the software.

After choosing the option "Connect with an existing account", I fill in my secret identifiers, and click OK. I get the following error:

![image](https://cloud.githubusercontent.com/assets/969136/22475354/036cd786-e7df-11e6-8a0e-0c16016fb66e.png)

	    Task exception was never retrieved
	future: <Task finished coro=<ConnectionConfigController.process() done, defined at sakia/gui/dialogs/connection_cfg/controller.py:103> exception=TypeError('unorderable types: NoneType() > int()',)>

	    ----
	    Traceback (most recent call last):

	  File "asyncio/tasks.py", line 239, in _step

	  File "sakia/gui/dialogs/connection_cfg/controller.py", line 168, in process

	  File "sakia/gui/dialogs/connection_cfg/model.py", line 77, in initialize_identity

	  File "sakia/data/processors/identities.py", line 139, in initialize_identity

	TypeError: unorderable types: NoneType() > int()

**Comment by c-geek** [comment]
I can click on "OK", but the process remains stuck on 66%. If I close the window, I get redirected to the Network window.

But I have no transactions in my wallet.

**Comment by Insoleet** [comment]
Do you reproduce this behaviour everytime you try ?

**Comment by c-geek** [comment]
Yes: 


	    Task exception was never retrieved
	future: <Task finished coro=<ConnectionConfigController.process() done, defined at sakia/gui/dialogs/connection_cfg/controller.py:103> exception=TypeError('unorderable types: NoneType() > int()',)>

	    ----
	    Traceback (most recent call last):

	  File "asyncio/tasks.py", line 239, in _step

	  File "sakia/gui/dialogs/connection_cfg/controller.py", line 168, in process

	  File "sakia/gui/dialogs/connection_cfg/model.py", line 77, in initialize_identity

	  File "sakia/data/processors/identities.py", line 139, in initialize_identity

	TypeError: unorderable types: NoneType() > int()

**Comment by Insoleet** [comment]
Did this issue happened with your main account ?

**Comment by Insoleet** [comment]
I'm still interested by the answer even if I closed the issue ! :)

**Comment by c-geek** [comment]
Yes, with my main account.

**Comment by Insoleet** [comment]
It's like if the URI http://gtest.duniter.org:10900/blockchain/memberships/cgeek return null in the written field. I wonder if there is a problem on duniter side.
