### ISSUE TITLE
Many error reports on startup

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#595]
It occurs every morning when I restart Sakia:

![image](https://cloud.githubusercontent.com/assets/969136/22541733/70b98aba-e928-11e6-8afc-478cfa5025c9.png)

        Task exception was never retrieved
    future: <Task finished coro=<NodeConnector.connect_current_block() done, defined at sakia/data/connectors/node.py:150> exception=SystemError('<built-in method emit of PyQt5.QtCore.pyqtBoundSignal object at 0x7effb47ec468> returned a result with an error set',)>

        ----
        Traceback (most recent call last):

      File "site-packages/aiohttp/connector.py", line 620, in _create_direct_connection

      File "asyncio/base_events.py", line 695, in create_connection

      File "asyncio/base_events.py", line 682, in create_connection

      File "asyncio/futures.py", line 361, in __iter__

      File "asyncio/tasks.py", line 296, in _wakeup

      File "asyncio/futures.py", line 274, in result

      File "asyncio/selector_events.py", line 414, in _sock_connect

    OSError: [Errno 22] Argument invalide

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):

      File "site-packages/aiohttp/connector.py", line 308, in connect

      File "site-packages/aiohttp/connector.py", line 597, in _create_connection

      File "site-packages/aiohttp/connector.py", line 643, in _create_direct_connection

    aiohttp.errors.ClientOSError: [Errno 22] Can not connect to fe80::b2c0:b69b:36e6:f895:60527 [Argument invalide]

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):

      File "sakia/data/connectors/node.py", line 160, in connect_current_block

      File "site-packages/aiohttp/client.py", line 540, in __aenter__

      File "site-packages/aiohttp/client.py", line 306, in _ws_connect

      File "site-packages/aiohttp/client.py", line 530, in __iter__

      File "site-packages/aiohttp/client.py", line 176, in _request

      File "site-packages/aiohttp/connector.py", line 318, in connect

    aiohttp.errors.ClientOSError: [Errno 22] Cannot connect to host fe80::b2c0:b69b:36e6:f895:60527 ssl:False [Can not connect to fe80::b2c0:b69b:36e6:f895:60527 [Argument invalide]]

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):

      File "site-packages/aiohttp/connector.py", line 620, in _create_direct_connection

      File "asyncio/base_events.py", line 695, in create_connection

      File "asyncio/base_events.py", line 682, in create_connection

      File "asyncio/futures.py", line 361, in __iter__

      File "asyncio/tasks.py", line 296, in _wakeup

      File "asyncio/futures.py", line 274, in result

      File "asyncio/selector_events.py", line 439, in _sock_connect_cb

    ConnectionRefusedError: [Errno 111] Connect call failed ('51.255.197.83', 8999)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):

      File "site-packages/aiohttp/connector.py", line 308, in connect

      File "site-packages/aiohttp/connector.py", line 597, in _create_connection

      File "site-packages/aiohttp/connector.py", line 643, in _create_direct_connection

    aiohttp.errors.ClientOSError: [Errno 111] Can not connect to peer.duniter.org:8999 [Connect call failed ('51.255.197.83', 8999)]

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):

      File "sakia/data/connectors/node.py", line 160, in connect_current_block

      File "site-packages/aiohttp/client.py", line 540, in __aenter__

      File "site-packages/aiohttp/client.py", line 306, in _ws_connect

      File "site-packages/aiohttp/client.py", line 530, in __iter__

      File "site-packages/aiohttp/client.py", line 176, in _request

      File "site-packages/aiohttp/connector.py", line 318, in connect

    aiohttp.errors.ClientOSError: [Errno 111] Cannot connect to host peer.duniter.org:8999 ssl:False [Can not connect to peer.duniter.org:8999 [Connect call failed ('51.255.197.83', 8999)]]

    During handling of the above exception, another exception occurred:

    sqlite3.OperationalError: database is locked

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):

      File "asyncio/tasks.py", line 241, in _step

      File "sakia/data/connectors/node.py", line 181, in connect_current_block

    SystemError: <built-in method emit of PyQt5.QtCore.pyqtBoundSignal object at 0x7effb47ec468> returned a result with an error set

**Comment by Insoleet** [comment]
You are restarting Sakia too fast and the lock on the db is still present.
Same issue as https://github.com/duniter/sakia/issues/588, fixed in next release !
