### ISSUE TITLE
Error when closing certification window

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#598]
When certifying someone from WoT view, and finally closing certification window:
```bash
DEBUG:bma:verified_get:Requesting lookup on endpoint BASIC_MERKLED_API cgeek.fr 88.174.120.187 10900
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<refresh() done, defined at sakia/gui/sub/user_information/controller.py:59> exception=RuntimeError('wrapped C/C++ object of type UserInformationView has been deleted',)>
Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/sub/user_information/controller.py", line 67, in refresh
  File "sakia/gui/sub/user_information/view.py", line 68, in display_identity_timestamps
RuntimeError: wrapped C/C++ object of type UserInformationView has been deleted
DEBUG:bma:verified_get:Requesting block on endpoint BASIC_MERKLED_API gtest.duniter.inso.ovh 80
```

**Comment by Insoleet** [comment]
Fixed in next release.
