### ISSUE TITLE
Error bug report

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#610]
With 0.30.7:
```bash
DEBUG:node:connect_peers:Received a peer : J78bP
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<NetworkService.discovery_loop() done, defined at sakia/services/network.py:203> exception=RuntimeError('coroutine raised StopIteration',)>
Traceback (most recent call last):
  File "sakia/services/network.py", line 226, in discovery_loop
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
RuntimeError: coroutine raised StopIteration
DEBUG:node:connect_peers:Received a peer : BmDso
```

**Comment by Insoleet** [comment]
Duplicate of https://github.com/duniter/sakia/issues/612
