### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#612]
With Sakia 0.30.11 Arch build:
```bash
DEBUG:network:handle_change:000055F7BE -> 000055F7BE
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<NetworkService.discovery_loop() done, defined at sakia/services/network.py:204> exception=RuntimeError('coroutine raised StopIteration',)>
Traceback (most recent call last):
  File "sakia/services/network.py", line 227, in discovery_loop
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
RuntimeError: coroutine raised StopIteration
DEBUG:node:connect_peers:Received a peer : CSjgc
DEBUG:network:handle_new_node:Stacking new peer documen
```

**Comment by Insoleet** [comment]
Should be fixed in 0.32.
