### ISSUE TITLE
Certificate check fail with Arch build on Fedora

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#621]
I can't connect on the money, that is may be because of SSL lib included on the build:
```bash
DEBUG:node:connect_current_block:[Errno 1] Cannot connect to host g1.duniter.org:443 ssl:True [Can not connect to g1.duniter.org:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]] : 4aCqw
DEBUG:node:connect_peers:[Errno 1] Cannot connect to host g1.duniter.org:443 ssl:True [Can not connect to g1.duniter.org:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]] : 4aCqw
DEBUG:node:connect_current_block:[Errno 1] Cannot connect to host g1.duniter.org:443 ssl:True [Can not connect to g1.duniter.org:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]] : 4aCqw
DEBUG:node:connect_peers:[Errno 1] Cannot connect to host g1.duniter.org:443 ssl:True [Can not connect to g1.duniter.org:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]] : 4aCqw
DEBUG:controller:check_connect:Is valid ? 
DEBUG:controller:check_connect:Is valid ? 
DEBUG:controller:check_connect:Is valid ? 
DEBUG:controller:check_connect:Is valid ? 
DEBUG:controller:check_connect:Is valid ? 
DEBUG:node:connect_peers:[Errno 1] Cannot connect to host g1.duniter.org:443 ssl:True [Can not connect to g1.duniter.org:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]] : 4aCqw
DEBUG:node:connect_current_block:[Errno 1] Cannot connect to host g1.duniter.org:443 ssl:True [Can not connect to g1.duniter.org:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]] : 4aCqw
```

**Comment by M5oul** [comment]
Yep, my computer accept to Let's Encrypt certificates.

Removing ssl lib doesn't works:
```bash
LOADER: Running main.py
Traceback (most recent call last):
  File "sakia/main.py", line 12, in <module>
  File "/home/inso/.pyenv/versions/3.5.2/envs/sakia-dev-35/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "sakia/app.py", line 6, in <module>
  File "/home/inso/.pyenv/versions/3.5.2/envs/sakia-dev-35/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "aiohttp/__init__.py", line 11, in <module>
  File "/home/inso/.pyenv/versions/3.5.2/envs/sakia-dev-35/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "aiohttp/connector.py", line 3, in <module>
  File "/home/inso/.pyenv/versions/3.5.2/envs/sakia-dev-35/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "ssl.py", line 98, in <module>
ImportError: No module named '_ssl'
Failed to execute script main
```

**Comment by Insoleet** [comment]
I think we need one system build per OS on linux sadly...

**Comment by M5oul** [comment]
Nah, it was ok with linux build.
I [have the qwerty issue](https://github.com/duniter/sakia/issues/609).
That's why I use the Arch one.
I may close this one and open the other one.
