### ISSUE TITLE
Erreur lors d'une recherche de membre

### ISSUE THREAD

**Issue by vincentux** [duniter/sakia#658]
J'ai voulu faire une recherche avec l' uid "cgeek", pour changer ;) mais : 
```
An unhandled exception occured
    ----
    Traceback (most recent call last):
  File "sakia/gui/navigation/identities/table_model.py", line 60, in data
AttributeError: 'IdentitiesFilterProxyModel' object has no attribute 'connection'
```

```
An unhandled exception occured
    ----
    Traceback (most recent call last):
  File "sakia/gui/navigation/identities/table_model.py", line 70, in data
AttributeError: 'IdentitiesFilterProxyModel' object has no attribute 'connection'
```

**Comment by Insoleet** [comment]
Fixed in 0.31.3
