### ISSUE TITLE
Can't connect to GTest with pubkey procedure

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#660]
I tried to connect again to GTest using my UID + pubkey, howerver I encountered a "No peers answered in the community", and when I try to close Sakia I get the following stack in the console.

Is Sakia 0.31 compliant with GTest?

```
Traceback (most recent call last):
  File "sakia/gui/navigation/network/table_model.py", line 90, in data
  File "sakia/data/processors/blockchain.py", line 51, in adjusted_ts
  File "sakia/data/processors/blockchain.py", line 88, in parameters
AttributeError: 'NoneType' object has no attribute 'parameters'
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "sakia/gui/navigation/network/table_model.py", line 90, in data
  File "sakia/data/processors/blockchain.py", line 51, in adjusted_ts
  File "sakia/data/processors/blockchain.py", line 88, in parameters
AttributeError: 'NoneType' object has no attribute 'parameters'
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "sakia/gui/navigation/network/table_model.py", line 90, in data
  File "sakia/data/processors/blockchain.py", line 51, in adjusted_ts
  File "sakia/data/processors/blockchain.py", line 88, in parameters
AttributeError: 'NoneType' object has no attribute 'parameters'


Erreur de segmentation (core dumped)
```

**Comment by Insoleet** [comment]
Sakia is not compatible with GTest anymore because of blockchain parameters. I'll fix the dirty  segfault, thought.
