### ISSUE TITLE
synchronisation inopérante

### ISSUE THREAD

**Issue by bou2fil** [duniter/sakia#661]
![sakia-pb4](https://cloud.githubusercontent.com/assets/23458989/24591743/c1ab35f4-1808-11e7-80f2-2113d0a6193d.png)
**Message affiché dans les détails de la fenêtre Critical error.** qui s'affiche sans arrêt (multiplication des fenêtres)

```
  Task exception was never retrieved
future: <Task finished coro=<NodeConnector.connect_peers() done, defined at sakia/data/connectors/node.py:271> exception=HttpProxyError("400, message='Bad Request'",)>

    ----
    Traceback (most recent call last):

  File "asyncio/tasks.py", line 239, in _step

  File "sakia/data/connectors/node.py", line 282, in connect_peers

  File "site-packages/aiohttp/client.py", line 595, in __aenter__

  File "site-packages/aiohttp/client.py", line 354, in _ws_connect

  File "site-packages/aiohttp/client.py", line 585, in __iter__

  File "site-packages/aiohttp/client.py", line 217, in _request

  File "site-packages/aiohttp/connector.py", line 370, in connect

  File "site-packages/aiohttp/connector.py", line 661, in _create_connection

  File "site-packages/aiohttp/connector.py", line 761, in _create_proxy_connection

aiohttp.errors.HttpProxyError: 400, message='Bad Request'
```

**Comment by Insoleet** [comment]
Did you configure a proxy server ?

**Comment by bou2fil** [comment]
J'ai suivi le tuto : https://forum.duniter.org/t/souci-install-sakia/957/34
Fait : rm -rf ~/.config/sakia
réinstallé sakia et ça a bien fonctionné

**Comment by Insoleet** [comment]
Je rouvre parce qu'il y a bien un problème quelque part. Je vaix au moins capture l'exception.

**Comment by Insoleet** [comment]
Devrait être corrigé avec l'utilisation de aiohttp 2.
