### ISSUE TITLE
Random network error

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#663]
StackTrace:

```

    Task exception was never retrieved
future: <Task finished coro=<NetworkService.discovery_loop() done, defined at sakia/services/network.py:161> exception=RuntimeError('coroutine raised StopIteration',)>

    ----
    Traceback (most recent call last):

  File "sakia/services/network.py", line 184, in discovery_loop

StopIteration


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "asyncio/tasks.py", line 239, in _step

RuntimeError: coroutine raised StopIteration
```

**Comment by Insoleet** [comment]
Should be fixed in next release.
