### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#669]
May be an [interesting dev doc](https://doc.qt.io/qt-5/highdpi.html)

**Comment by Insoleet** [comment]
Should be fixed on dev branch.

**Comment by M5oul** [comment]
Images are bigger but not buttons:

![Sakia](http://pix.toile-libre.org/upload/original/1493637634.png)

**Comment by M5oul** [comment]
Same.

**Comment by M5oul** [comment]
```bash
Traceback (most recent call last):
  File "src/sakia/main.py", line 120, in <module>
    window = MainWindowController.startup(app)
  File "/home/moul/projects/sakia_git/src/sakia/gui/main_window/controller.py", line 74, in startup
    toolbar = ToolbarController.create(app, navigation)
  File "/home/moul/projects/sakia_git/src/sakia/gui/main_window/toolbar/controller.py", line 50, in create
    view = ToolbarView(None)
  File "/home/moul/projects/sakia_git/src/sakia/gui/main_window/toolbar/view.py", line 64, in __init__
    self.button_network.setSize(self.button_network.size()*dpi_ratio())
AttributeError: 'QPushButton' object has no attribute 'setSize'
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<get_last_version() running at /home/moul/projects/sakia_git/src/sakia/app.py:189>>
sys:1: RuntimeWarning: coroutine 'get_last_version' was never awaited
```

**Comment by M5oul** [comment]
Much better:
![](http://pix.toile-libre.org/upload/original/1493639486.png)

A bit too much big.
