### ISSUE TITLE
Right click on UID/pubkey in Transfers

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#673]
On a right click on `TENGx` pubkey, right after a fresh new installation and the connection of `cgeek` account, I got this error:

```

    An unhandled exception occured

    ----
    Traceback (most recent call last):

  File "sakia/gui/navigation/txhistory/controller.py", line 74, in history_context_menu

  File "sakia/gui/navigation/txhistory/model.py", line 70, in table_data

  File "sakia/services/identities.py", line 451, in get_identity

  File "sakia/data/processors/identities.py", line 113, in get_identity

  File "sakia/data/repositories/identities.py", line 85, in get_all

sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

```

So I cannot copy a pubkey from the transfers list. It is not a blocking issue, I can find the pubkey of Remuniter in other ways.

**Comment by Insoleet** [comment]
Yes, I noticed it after releasing. Will be fixed in 0.31.6.
