### ISSUE TITLE
Crash issue on new Sakia install

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#678]
If you run Sakia for the first time and choose to close this window on start:

![image](https://cloud.githubusercontent.com/assets/969136/24949820/3936be1e-1f6f-11e7-84d8-82537aa41460.png)

Then you will fall in a long list of errors:

```
    Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f267c0609b0>

    ----
```

```
    Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f267c0609b0>

    ----
```

```
    An unhandled exception occured

    ----
    Traceback (most recent call last):

  File "sakia/gui/navigation/network/table_model.py", line 90, in data

  File "sakia/data/processors/blockchain.py", line 51, in adjusted_ts

  File "sakia/data/processors/blockchain.py", line 88, in parameters

AttributeError: 'NoneType' object has no attribute 'parameters'
```

**Comment by Insoleet** [comment]
Fixed in 0.32.
