### ISSUE TITLE
Can't add a pubkey as it's wrong format

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#687]
```
DEBUG:node:connect_current_block:Received a block : 5dzkz
DEBUG:node:refresh_block:Requesting connection info: duniter-g1.vincentux.fr:443
DEBUG:identities:execute_requests:2001
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<check_pubkey() done, defined at /home/moul/projects/sakia_git/src/sakia/gui/dialogs/connection_cfg/controller.py:293> exception=InvalidStateError('FINISHED: <Future finished result=None>',)>
Traceback (most recent call last):
  File "/home/moul/.pyenv/versions/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/moul/projects/sakia_git/src/sakia/gui/dialogs/connection_cfg/controller.py", line 315, in check_pubkey
    self.step_key.set_result(None)
  File "/home/moul/.pyenv/versions/3.5.2/lib/python3.5/asyncio/futures.py", line 329, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <Future finished result=None>
DEBUG:node:refresh_block:Changed block 15503 -> 15503
DEBUG:network:handle_change:000004B819 -> 000004B819
DEBUG:controller:process:Error code 1002 - Pubkey format is incorrect, must be a Base58 string
DEBUG:controller:process:Begin process
DEBUG:controller:process:Licence step
DEBUG:controller:process:Key step
DEBUG:controller:process:Pubkey mode
```

**Comment by Insoleet** [comment]
This is a bit short. Can you add some explanation about what you are trying to do ?

**Comment by M5oul** [comment]
I tried to add connection with a pubkey with following pubkey `DZ6EiFKnXWEFkjVJYj8Rmrw5XPLgMCMF4xFwLiPRdRwJ` as a new account.
I can't add it with following message: `Pubkey format is incorrect` `Broadcast 1001 …`

**Comment by M5oul** [comment]
```bash
DEBUG:controller:process:Error code 1002 - Pubkey format is incorrect, must be a Base58 string
```
on upper logs.
It's seems two bugs happen same time.

**Comment by Insoleet** [comment]
I can't reproduce this problem here. Are you sure you are pasting the correct pubkey ?

**Comment by M5oul** [comment]
It's fixed. It works, but I get following error:
```bash
DEBUG:network:handle_change:00001824E2 -> 00001824E2
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<BlockchainService.handle_blockchain_progress() done, defined at /home/moul/projects/sakia_git/src/sakia/services/blockchain.py:52> exception=KeyError(Connection(currency='g1', pubkey='DZ6EiFKnXWEFkjVJYj8Rmrw5XPLgMCMF4xFwLiPRdRwJ', uid='', scrypt_N=4096, scrypt_r=16, scrypt_p=1, blockstamp=<duniterpy.documents.block.BlockUID object at 0x7fafc40e1588>, salt=Attribute(name='salt', default=NOTHING, validator=None, repr=True, cmp=False, hash=False, init=False, convert=<class 'str'>, metadata=mappingproxy({})), password=''),)>
Traceback (most recent call last):
  File "/home/moul/.pyenv/versions/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/moul/projects/sakia_git/src/sakia/services/blockchain.py", line 69, in handle_blockchain_progress
    destructions = await self._sources_service.refresh_sources(new_tx, new_dividends)
  File "/home/moul/projects/sakia_git/src/sakia/services/sources.py", line 177, in refresh_sources
    destructions[conn] += await self.refresh_sources_of_pubkey(conn.pubkey, transactions[conn],
KeyError: Connection(currency='g1', pubkey='DZ6EiFKnXWEFkjVJYj8Rmrw5XPLgMCMF4xFwLiPRdRwJ', uid='', scrypt_N=4096, scrypt_r=16, scrypt_p=1, blockstamp=<duniterpy.documents.block.BlockUID object at 0x7fafc40e1588>, salt=Attribute(name='salt', default=NOTHING, validator=None, repr=True, cmp=False, hash=False, init=False, convert=<class 'str'>, metadata=mappingproxy({})), password='')
DEBUG:network:handle_new_node:Stacking new peer document : 4aCqwikTaTPBRQLGiLHohuoJLPmLephy9eDtgCWLMwBk
DEBUG:network:handle_new_node:Stacking new peer document : 5cnvo5bmR8QbtyNVnkDXWq6n5My6oNLd1o6auJApGCsv
DEBUG:network:handle_new_node:Stacking new peer document : 2ny7YAdmzReQxAayyJZsyVYwYhVyax2thKcGknmQy5nQ
DEBUG:network:handle_new_node:Stacking new peer document : 38MEAZN68Pz1DTvT3tqgxx4yQP6snJCQhPqEFxbDk4aE
```

**Comment by Insoleet** [comment]
Can you share your database ?
