### ISSUE TITLE
Error testing RML9 plugin

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#699]
```bash
python src/sakia/main.py  --withplugin ../sakia-plugin-example/plugin_example.zip 
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "src/sakia/main.py", line 120, in <module>
    window = MainWindowController.startup(app)
  File "/home/moul/projects/sakia_git/src/sakia/gui/main_window/controller.py", line 92, in startup
    main_window.model.load_plugins(main_window)
  File "/home/moul/projects/sakia_git/src/sakia/gui/main_window/model.py", line 18, in load_plugins
    self.app.plugins_dir.with_plugin.module.plugin_exec(self.app, main_window)
AttributeError: 'NoneType' object has no attribute 'plugin_exec'
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<get_last_version() running at /home/moul/projects/sakia_git/src/sakia/app.py:192>>
sys:1: RuntimeWarning: coroutine 'get_last_version' was never awaited
```

**Comment by M5oul** [comment]
Fix [not well explained on documentation](https://github.com/duniter/sakia/blob/dev/doc/plugin_development.md):
```bash
python gen_resources.py
python setup.py build
```
