### ISSUE TITLE
Revocation document on Windows 64

### ISSUE THREAD

**Issue by mcl12345** [duniter/sakia#728]
After I saved my revocation document , I have this bug when I saved to sakia installation

    Task exception was never retrieved
     future: <Task finished coro=<check_register() done, defined at 
     sakia\gui\dialogs\connection_cfg\controller.py:386> exception=PermissionError(13, 'Permission denied')>

    ----
    Traceback (most recent call last):

     File "asyncio\tasks.py", line 240, in _step

     File "sakia\gui\dialogs\connection_cfg\controller.py", line 399, in check_register

     File "sakia\gui\dialogs\connection_cfg\controller.py", line 282, in action_save_revocation

    PermissionError: [Errno 13] Permission denied: 'C:/Program Files (x86)/Sakia/revocation_document.txt'

**Comment by mcl12345** [comment]
Finally I can saved it to Documents , and it works
