### ISSUE TITLE
Bug on the APi

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#732]
```bash
DEBUG:bma:verified_get:Requesting requirements on endpoint BASIC_MERKLED_API duniter.lamessen.me 80
DEBUG:bma:verified_get:Requesting requirements on endpoint BASIC_MERKLED_API duniter.floth.fr 80
DEBUG:identities:load_requirements:Error code 2021 - No identity matching this pubkey or uid
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<NetworkService.discovery_loop() done, defined at /home/moul/projects/sakia_git/src/sakia/services/network.py:169> exception=IndexError('list index out of range',)>
Traceback (most recent call last):
  File "/home/moul/projects/sakia_git/src/sakia/services/network.py", line 208, in discovery_loop
    self._processor.update_node(node)
  File "/home/moul/projects/sakia_git/src/sakia/data/processors/nodes.py", line 65, in update_node
    other_node = self._repo.get_one(currency=node.currency, pubkey=node.pubkey)
  File "/home/moul/projects/sakia_git/src/sakia/data/repositories/nodes.py", line 75, in get_one
    return Node(*data)
  File "<attrs generated init 5b3ef808cb87d2e0c7d21544e08129b3ad66e6b1>", line 4, in __init__
    self.endpoints = __attr_convert_endpoints(endpoints)
  File "/home/moul/projects/sakia_git/src/sakia/data/entities/node.py", line 16, in _tuple_of_endpoints
    conv.append(endpoint(s))
  File "/home/moul/.pyenv/versions/sakia-env/lib/python3.6/site-packages/duniterpy/documents/peer.py", line 106, in endpoint
    return UnknownEndpoint.from_inline(value)
  File "/home/moul/.pyenv/versions/sakia-env/lib/python3.6/site-packages/duniterpy/documents/peer.py", line 133, in from_inline
    api = inline.split()[0]
IndexError: list index out of range
DEBUG:node:safe_request:[2t6NP] 
DEBUG:node:refresh_block:[2t6NP] Changed block 56740 -> 56740
DEBUG:node:refresh_block:[2t6NP] Could not connect to any BMA endpoint
ERROR:root:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7faba4088470>
DEBUG:node:connect_current_block:[EZBtA] Received a block
```

**Comment by Insoleet** [comment]
Canno't reproduce.
