### ISSUE TITLE
IndexError when clicking on "View in WOT"

### ISSUE THREAD

**Issue by mcl12345** [duniter/sakia#739]
In "Search an identity"
 When I was clicking on "View in Web of Trust"

     Task exception was never retrieved future: 
    <Task finished coro=<NetworkService.discovery_loop() done, 
    defined at sakia\services\network.py:169> exception=IndexError('list index out of range',)>

    ----
    Traceback (most recent call last):

    File "asyncio\tasks.py", line 240, in _step

    File "sakia\services\network.py", line 208, in discovery_loop

    File "sakia\data\processors\nodes.py", line 65, in update_node

    File "sakia\data\repositories\nodes.py", line 75, in get_one

    File "<attrs generated init 38c9b84fd22c164ab7755aa5b534f26182c5ae76>", line 4, in __init__
    self.endpoints = __attr_convert_endpoints(endpoints)

    File "sakia\data\entities\node.py", line 16, in _tuple_of_endpoints

    File "site-packages\duniterpy\documents\peer.py", line 106, in endpoint

    File "site-packages\duniterpy\documents\peer.py", line 133, in from_inline

      IndexError: list index out of range

**Comment by Insoleet** [comment]
Interesting bug. Can you share your g1.db file from your home dir `~/.config/sakia/Default Profile/` ?

**Comment by mcl12345** [comment]
https://drive.google.com/file/d/0BxLp8QADQWfBU0FiNWZnVFhiakU/view?usp=sharing

**Comment by mcl12345** [comment]
I didn't find the ressource ~/.config/sakia

**Comment by Insoleet** [comment]
On windows, replace .config vu %APPDATA%

**Comment by mcl12345** [comment]
https://drive.google.com/open?id=0BxLp8QADQWfBYUJBaWNaajBPSEk

**Comment by Insoleet** [comment]
Should be fixed in 0.32.3
