### ISSUE TITLE
IndexError when launching the app

### ISSUE THREAD

**Issue by mcl12345** [duniter/sakia#743]
First error :

      An unhandled exception occured

     ----
     Traceback (most recent call last):

     File "sakia\main.py", line 100, in <module>

     File "sakia\app.py", line 90, in startup

     File "sakia\app.py", line 106, in load_profile

     File "sakia\app.py", line 118, in instanciate_services

     File "sakia\data\processors\nodes.py", line 18, in initialize_root_nodes

     File "sakia\data\processors\nodes.py", line 103, in nodes

    File "sakia\data\repositories\nodes.py", line 101, in get_all

    File "sakia\data\repositories\nodes.py", line 101, in <listcomp>

    File "<attrs generated init 1c8547ea9df2e8cab057e3c1c29153bcd7e49740>", line 4, in __init__
    self.endpoints = __attr_convert_endpoints(endpoints)

    File "sakia\data\entities\node.py", line 16, in _tuple_of_endpoints

    File "site-packages\duniterpy\documents\peer.py", line 106, in endpoint

    File "site-packages\duniterpy\documents\peer.py", line 133, in from_inline

    IndexError: list index out of range

**Comment by mcl12345** [comment]
Task was destroyed but it is pending!
       task: <Task pending coro=<get_last_version() running at sakia\app.py:192>>

     ----

**Comment by Insoleet** [comment]
Should be fixed in 0.32.3
