### ISSUE TITLE
api_list.append(type(e).API)  has no attribute 'API'

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#744]
```bash
DEBUG:table_model:init_nodes:Init nodes table
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "src/sakia/main.py", line 120, in <module>
    window = MainWindowController.startup(app)
  File "/home/moul/projects/sakia_git/src/sakia/gui/main_window/controller.py", line 73, in startup
    navigation = NavigationController.create(None, app)
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/controller.py", line 64, in create
    navigation.init_navigation()
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/controller.py", line 111, in init_navigation
    self.parse_node(node)
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/controller.py", line 99, in parse_node
    component = component_class.create(self, self.model.app, **node_data['dependencies'])
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/network/controller.py", line 40, in create
    txhistory = cls(parent, view, model)
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/network/controller.py", line 24, in __init__
    table_model = self.model.init_network_table_model()
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/network/model.py", line 28, in init_network_table_model
    model.init_nodes()
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/network/table_model.py", line 244, in init_nodes
    data = self.data_node(node, current_buid)
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/network/table_model.py", line 206, in data_node
    api_list.append(type(e).API)
AttributeError: type object 'NoneType' has no attribute 'API'
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<get_last_version() running at /home/moul/projects/sakia_git/src/sakia/app.py:194>>
sys:1: RuntimeWarning: coroutine 'get_last_version' was never awaited
```

**Comment by Insoleet** [comment]
I'd love if you could share your g1.db file !

**Comment by M5oul** [comment]
- [g1.db](https://moul.re/jirafeau/f.php?h=3fcioUYs&d=1)

**Comment by M5oul** [comment]
Great it's fixed!
