### ISSUE TITLE
local variable 'sort_certifier' referenced before assignment

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#745]
```bash
DEBUG:controller:dates_changed:Changed dates
DEBUG:controller:dates_changed:Changed dates
'attr_dict'
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<draw_graph() done, defined at /home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/controller.py:55> exception=UnboundLocalError("local variable 'sort_certifier' referenced before assignment",)>
Traceback (most recent call last):
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/controller.py", line 65, in draw_graph
    self.refresh()
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/controller.py", line 73, in refresh
    self.view.display_wot(nx_graph, self.model.identity)
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/view.py", line 44, in display_wot
    self.graphics_view.scene().update_wot(nx_graph, identity)
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/scene.py", line 149, in update_wot
    certifiers_graph_pos = WotScene.certifiers_partial_layout(nx_graph, identity.pubkey, scale=200*dpi_ratio())
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/scene.py", line 85, in certifiers_partial_layout
    for n in sort_certifier:
UnboundLocalError: local variable 'sort_certifier' referenced before assignment
DEBUG:node:connect_current_block:[APwgh] Cannot connect to host 127.0.0.1:10901 ssl:False [Connect call failed ('127.0.0.1', 10901)] : APwgh
DEBUG:node:connect_current_block:[8KTEF] Cannot connect to host 167.114.232.189:8999 ssl:False [Connect call failed ('167.114.232.189', 8999)] : 8KTEF
DEBUG:node:connect_peers:[APwgh] Cannot connect to host 127.0.0.1:10901 ssl:False [Connect call failed ('127.0.0.1', 10901)]
```

**Comment by Insoleet** [comment]
Should be fixed in 0.32.3
