### ISSUE TITLE
KeyError: 'attr_dict'

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#747]
```bash
DEBUG:controller:dates_changed:Changed dates
DEBUG:controller:dates_changed:Changed dates
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<draw_graph() done, defined at /home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/controller.py:55> exception=KeyError('attr_dict',)>
Traceback (most recent call last):
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/controller.py", line 65, in draw_graph
    self.refresh()
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/controller.py", line 73, in refresh
    self.view.display_wot(nx_graph, self.model.identity)
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/view.py", line 44, in display_wot
    self.graphics_view.scene().update_wot(nx_graph, identity)
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/scene.py", line 146, in update_wot
    certifiers_graph_pos = WotScene.certifiers_partial_layout(nx_graph, identity.pubkey, scale=200*dpi_ratio())
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/scene.py", line 80, in certifiers_partial_layout
    sort_certifier = sorted(certifier, key=lambda node_: node_[1]['attr_dict']['text'].lower())
  File "/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/scene.py", line 80, in <lambda>
    sort_certifier = sorted(certifier, key=lambda node_: node_[1]['attr_dict']['text'].lower())
KeyError: 'attr_dict'
DEBUG:node:connect_current_block:[2ny7Y] Cannot connect to host 88.174.120.187:10901 ssl:False [Connect call failed ('88.174.120.187', 10901)] : 2ny7Y
```

**Comment by Insoleet** [comment]
Did you update all the libraries ?

**Comment by M5oul** [comment]
I can't reproduced it upgrading all libs.
