### ISSUE TITLE
Erreur Sakia 0.32.3

### ISSUE THREAD

**Issue by vincentux** [duniter/sakia#749]
Erreur sur une Xubuntu

```
ERROR:root:An unhandled exception occured
    Traceback (most recent call last):
      File "sakia/main.py", line 100, in <module>
      File "sakia/app.py", line 91, in startup
      File "sakia/app.py", line 107, in load_profile
      File "sakia/app.py", line 119, in instanciate_services
      File "sakia/data/processors/nodes.py", line 18, in initialize_root_nodes
      File "sakia/data/processors/nodes.py", line 103, in nodes
      File "sakia/data/repositories/nodes.py", line 101, in get_all
      File "sakia/data/repositories/nodes.py", line 101, in <listcomp>
      File "<attrs generated init 6ad568dd179460b9356d20f6f6d25da56507d17d>", line 4, in __init__
        self.endpoints = __attr_convert_endpoints(endpoints)
      File "sakia/data/entities/node.py", line 17, in _tuple_of_endpoints
      File "site-packages/duniterpy/documents/peer.py", line 99, in endpoint
      File "site-packages/duniterpy/documents/peer.py", line 275, in from_inline
    duniterpy.documents.document.MalformedDocumentError: Could not parse field WS2P
    [7499] Failed to execute script main
    [7499] LOADER: OK.
    [7499] LOADER: Cleaning up Python interpreter.
    ERROR:root:Task was destroyed but it is pending!
    task: <Task pending coro=<get_last_version() running at sakia/app.py:194>>
    sys:1: RuntimeWarning: coroutine 'get_last_version' was never awaited
    [7498] LOADER: Back to parent (RC: 255)
    [7498] LOADER: Doing cleanup
    [7498] LOADER: Freeing archive status for /opt/sakia/sakia.bin
```

Et ici la BDD : 
https://framadrop.org/r/riGw5DYea_#3DfpPydax7uvCO2hg/BK/tBtWhZr5ccMTVv6tbRBd8k=

**Comment by M5oul** [comment]
Similar to this one https://github.com/duniter/sakia/issues/746.

**Comment by vincentux** [comment]
trop rapide @M5oul ;)

**Comment by Insoleet** [comment]
Corrigé en 0.32.4
