### ISSUE TITLE
Sakia, which seems incompatible with a freshly new money.

### ISSUE THREAD

**Issue by Folatt** [duniter/sakia#761]
root_servers.yml
```
Guilder-Test:
  display: European Basic Guilder Test 
  nodes:
    AbE4R2fg4hmf6FPYuSuxx9MC9abnSMaPPenoYp8kHsf6:
    - "BMAS duniter-folatt.nohost.me 443"
```

My attempt to reach my node.

```
[me@Main-Computer sakia]$ sakia -d --currency=Guilder-Test
[11799] PyInstaller Bootloader 3.x
[11799] LOADER: executable is /opt/sakia/sakia.bin
[11799] LOADER: homepath is /opt/sakia
[11799] LOADER: _MEIPASS2 is NULL
[11799] LOADER: archivename is /opt/sakia/sakia.bin
[11799] LOADER: Extracting binaries
[11799] LOADER: Executing self as child
[11799] LOADER: set _MEIPASS2 to /opt/sakia
[11799] LOADER: LD_LIBRARY_PATH=/opt/sakia
[11800] PyInstaller Bootloader 3.x
[11800] LOADER: executable is /opt/sakia/sakia.bin
[11800] LOADER: homepath is /opt/sakia
[11800] LOADER: _MEIPASS2 is /opt/sakia
[11800] LOADER: archivename is /opt/sakia/sakia.bin
[11800] LOADER: Already in the child - running user's code.
[11800] LOADER: Python library: /opt/sakia/libpython3.5m.so.1.0
[11800] LOADER: Loaded functions from Python library.
[11800] LOADER: Manipulating environment (sys.path, sys.prefix)
[11800] LOADER: Pre-init sys.path is /opt/sakia/base_library.zip:/opt/sakia
[11800] LOADER: sys.prefix is /opt/sakia
[11800] LOADER: Setting runtime options
[11800] LOADER: Initializing python
[11800] LOADER: Overriding Python's sys.path
[11800] LOADER: Post-init sys.path is /opt/sakia/base_library.zip:/opt/sakia
[11800] LOADER: Setting sys.argv
[11800] LOADER: setting sys._MEIPASS
[11800] LOADER: importing modules from CArchive
[11800] LOADER: extracted struct
[11800] LOADER: callfunction returned...
[11800] LOADER: extracted pyimod01_os_path
[11800] LOADER: callfunction returned...
[11800] LOADER: extracted pyimod02_archive
[11800] LOADER: callfunction returned...
[11800] LOADER: extracted pyimod03_importers
[11800] LOADER: callfunction returned...
[11800] LOADER: Installing PYZ archive with Python modules.
[11800] LOADER: PYZ archive: out00-PYZ.pyz
[11800] LOADER: Running pyiboot01_bootstrap.py
[11800] LOADER: Running pyi_rth_qt5.py
[11800] LOADER: Running pyi_rth_multiprocessing.py
[11800] LOADER: Running pyi_rth_pkgres.py
[11800] LOADER: Running main.py
DEBUG:meta:prepare:Initializing meta database
DEBUG:meta:upgrade_database:Begin upgrade of database...
DEBUG:meta:upgrade_database:End upgrade of database...
DEBUG:network:add_connector:AbE4R connected
DEBUG:blockchain:initialize_blockchain:Requesting blockchain parameters
DEBUG:bma:verified_get:Requesting parameters on endpoint BMAS duniter-folatt.nohost.me 443
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "sakia/main.py", line 112, in <module>
  File "site-packages/quamash/__init__.py", line 263, in run_until_complete
RuntimeError: Event loop stopped before Future completed.
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "site-packages/quamash/__init__.py", line 231, in <lambda>
  File "site-packages/quamash/__init__.py", line 345, in call_soon
  File "site-packages/quamash/__init__.py", line 322, in call_later
  File "site-packages/quamash/__init__.py", line 339, in _add_callback
AttributeError: 'NoneType' object has no attribute 'append'
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<NetworkService.discovery_loop() running at sakia/services/network.py:179> wait_for=<Future pending cb=[Task._wakeup()]>>
ERROR:quamash._QEventLoop:Unhandled error in custom exception handler
context: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<NetworkService.discovery_loop() running at sakia/services/network.py:179> wait_for=<Future pending cb=[Task._wakeup()]>>}
Traceback (most recent call last):
  File "site-packages/quamash/__init__.py", line 185, in timerEvent
  File "site-packages/quamash/__init__.py", line 328, in upon_timeout
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/quamash/__init__.py", line 543, in call_exception_handler
  File "sakia/main.py", line 53, in async_exception_handler
  File "sakia/main.py", line 76, in exception_message
SystemError: <built-in method exec of QMessageBox object at 0x7fb93c083708> returned a result with an error set
Error in sys.excepthook:
Segmentation fault (core dumped)
```

**Comment by Insoleet** [comment]
Ok so I cannot join your node. Is it still up ?
