### ISSUE TITLE
Critical error au lancement après interruption réseau

### ISSUE THREAD

**Issue by fbuland** [duniter/sakia#762]
v.0.32.6
Interruption réseau (Wifi sur mon téléphone).
J'ai fermé Sakia puis après quelques minutes l'ai relancé.
Critical error au lancement :
    Task exception was never retrieved
future: <Task finished coro=<get_last_version() done, defined at sakia/app.py:194> exception=AttributeError("module 'aiohttp' has no attribute 'errors'",)>
    ----
    Traceback (most recent call last):
  File "sakia/app.py", line 200, in get_last_version
  File "site-packages/aiohttp/helpers.py", line 104, in __await__
  File "site-packages/aiohttp/client.py", line 269, in _request
  File "site-packages/aiohttp/connector.py", line 392, in connect
  File "site-packages/aiohttp/connector.py", line 737, in _create_connection
  File "site-packages/aiohttp/connector.py", line 796, in _create_direct_connection
  File "asyncio/base_events.py", line 762, in create_connection
  File "asyncio/selector_events.py", line 451, in sock_connect
  File "asyncio/futures.py", line 380, in __iter__
  File "asyncio/tasks.py", line 304, in _wakeup
  File "asyncio/futures.py", line 285, in result
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sakia/app.py", line 218, in get_last_version
  File "site-packages/async_timeout/__init__.py", line 35, in __exit__
  File "site-packages/async_timeout/__init__.py", line 80, in _do_exit
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "asyncio/tasks.py", line 241, in _step
  File "sakia/app.py", line 219, in get_last_version
AttributeError: module 'aiohttp' has no attribute 'errors'

 J'ai du relancé Sakia 3 fois (mais toujours avec ma connexion 3G instable) pour qu'il n'y ait plus cette erreur. Je pense le temps qu'il reprenne correctement sur les données.

**Comment by Insoleet** [comment]
Merci pour le rapport de bug, les RML sont toujours un bon moment pour stress test les logiciels dans des connexions pourries :)

**Comment by Insoleet** [comment]
Sera corrigé en 0.32.7.
