### ISSUE TITLE
Bug !?

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#765]
En rajoutant un 10ème pubkey dans ma liste de comptes : 

    Task exception was never retrieved
future: <Task finished coro=<BlockchainService.handle_blockchain_progress() done, defined at sakia/services/blockchain.py:54> exception=OperationalError('unable to open database file',)>

    ----
    Traceback (most recent call last):

  File "asyncio/tasks.py", line 240, in _step

  File "sakia/services/blockchain.py", line 75, in handle_blockchain_progress

  File "sakia/services/blockchain.py", line 44, in handle_new_blocks

  File "sakia/data/processors/blockchain.py", line 357, in handle_new_blocks

  File "sakia/data/repositories/blockchains.py", line 50, in update

sqlite3.OperationalError: unable to open database file

**Comment by Insoleet** [comment]
Tu avais une seule instance de Sakia démarrée ?

Ton disque n'est pas plein ?

**Comment by galuel** [comment]
Mon disque est loin d'être plein et je ne démarre qu'un Sakia à la fois oui.
