### ISSUE TITLE
Bug ? : undefined symbol: drmGetDevices2

### ISSUE THREAD

**Issue by vincentux** [duniter/sakia#768]
Salut,
finalement je fais une issue :/ 

Sakia 0.32.8 .deb
OS : Xubuntu 17.10

```
PyInstaller Bootloader 3.x
LOADER: executable is /opt/sakia/sakia.bin
LOADER: homepath is /opt/sakia
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /opt/sakia/sakia.bin
LOADER: pyi_arch_check_cookie failed
LOADER: Search for cookieLOADER: package found skipping digital signature in /opt/sakia/sakia.bin
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /opt/sakia
LOADER: LD_LIBRARY_PATH=/opt/sakia
PyInstaller Bootloader 3.x
LOADER: executable is /opt/sakia/sakia.bin
LOADER: homepath is /opt/sakia
LOADER: _MEIPASS2 is /opt/sakia
LOADER: archivename is /opt/sakia/sakia.bin
LOADER: pyi_arch_check_cookie failed
LOADER: Search for cookieLOADER: package found skipping digital signature in /opt/sakia/sakia.bin
LOADER: Already in the child - running user's code.
LOADER: Python library: /opt/sakia/libpython3.5m.so.1.0
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is /opt/sakia/base_library.zip:/opt/sakia
LOADER: sys.prefix is /opt/sakia
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is /opt/sakia/base_library.zip:/opt/sakia
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_qt5.py
LOADER: Running pyi_rth_qt5plugins.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running main.py
Traceback (most recent call last):
  File "sakia/main.py", line 8, in <module>
  File "/home/travis/.pyenv/versions/3.5.4/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2
Failed to execute script main
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /opt/sakia/sakia.bin
```

**Comment by Tristramg** [comment]
J’ai le même problème. En voyant https://github.com/fman-users/fman/issues/119

J’ai fait
`cd /opt/sakia`
`sudo mv libdrm.so.2 libdrm.so.2.meh`

Et c’est bon.

Mes compétences ayant leurs limites, je peux pas aider à savoir comment éviter ce soucis, tout en s’assurant que ça fonctionne sur différentes plateformes.
