### ISSUE TITLE
Cannot launch on OS X (0.32.8)

### ISSUE THREAD

**Issue by brabalan** [duniter/sakia#774]
If I try `open sakia.app` I get an error
```
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/sakia.app.
```

If I try to directly launch the binary `sakia.bin` I get a more useful error
```
Failed to execute script pyi_rth_qt5plugins
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_qt5plugins.py", line 46, in <module>
  File "/Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: dlopen(/Applications/sakia.app/Contents/MacOS/PyQt5.QtCore.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/QtCore
  Referenced from: /Applications/sakia.app/Contents/MacOS/PyQt5.QtCore.cpython-35m-darwin.so
  Reason: image not found
```

**Comment by Insoleet** [comment]
Could you try to build sakia by yourself and check if this works?

**Comment by brabalan** [comment]
Unfortunately I have no idea how to install all the dependencies.

**Comment by Insoleet** [comment]
Please take a look at https://twitter.com/lobsters/status/952787482122240000

**Comment by Insoleet** [comment]
Please take a look at

**Comment by brabalan** [comment]
Thank you for the link (maybe you should put it in the README instead of the link to the wiki.)

A couple comments on the installation:
- qt5 is now the default in homebrew
- does one need to install PyQT5? (I did, but it's in a code block that is about Linux)

After installation, if I run `open sakia.app`, I get the same error as before.

Running from source works, but I don't see any transactions and my balance is at 0.

**Comment by Insoleet** [comment]
> Running from source works, but I don't see any transactions and my balance is at 0.

Well this is weird, OSX or not this should not have happened. Maybe Sakia cannot reach the network ? What is the current block you are seeing at the bottom of the window ?

**Comment by brabalan** [comment]
Here are two screenshots. What I see are transactions that happened after I started Sakia.

<img width="1260" alt="screen shot 2018-01-15 at 14 55 45" src="https://user-images.githubusercontent.com/1021637/34945686-640a1c4c-fa04-11e7-8de2-8f557be65c2c.png">

<img width="1260" alt="screen shot 2018-01-15 at 14 57 03" src="https://user-images.githubusercontent.com/1021637/34945691-681c6998-fa04-11e7-815d-eebccb7fe390.png">

**Comment by Insoleet** [comment]
Can you remove your connection and add it back ? (right click on it to remove it)

**Comment by brabalan** [comment]
@Insoleet it worked, thanks.

So what can I do to help debug the initial bug: even when compiling it myself, I cannot launch the binary version of sakia. Using the source code version works.

**Comment by Insoleet** [comment]
On pyinstaller issues tracking, someone seems to have the same problem : https://github.com/pyinstaller/pyinstaller/issues/1988

Could you try with latest pyinstaller version, installed from git ?

**Comment by brabalan** [comment]
I'm not sure this would solve the issue, as the mentioned patch was integrated in pyinstaller 3.2.1 and I have 3.3.1.

I was able to go further. I can launch the binary at `dist/sakia/sakia.bin`. If I try to launch the binary at `dist/sakia.app/Contents/MacOS/sakia.bin`, I get an error saying the directory `dist/sakia.app/Contents/MacOS/Python` is not there. I can confirm it is missing:

```
[schmitta@top:~/src/sakia/dist/sakia.app/Contents/MacOS on master]
% ll
total 7592
-rwxr-xr-x+ 1 schmitta  staff    48K Jan 15 10:34 _struct.so
-rwxr-xr-x+ 1 schmitta  staff   3.6M Jan 15 10:34 sakia.bin
-rwxr-xr-x+ 1 schmitta  staff    32K Jan 15 10:34 zlib.so
```

It seems that some things are not compiled in the `dist/sakia.app/Contents/MacOS` folder.

**Comment by Letiteuf55** [comment]
Same issue here...

**Comment by Insoleet** [comment]
I think it would be best if you would open an issue on pyinstaller side.

**Comment by brabalan** [comment]
The turnaround seems to work. If I do `cp -a dist/sakia/* dist/sakia.app/Contents/MacOS` after running `pyinstaller`, the app launches. (There are some errors but I'll report them in another issue.)

**Comment by brabalan** [comment]
After updating with the latest commit, launching the OS X app works with no error.

**Comment by Insoleet** [comment]
Perfect ! We only miss a small commit to : 
  - Fix documentation
  - Apply workaround to travis script which builds OSX releases

**Comment by Insoleet** [comment]
What is weird is that I was already copying these files : 

https://github.com/duniter/sakia/blob/master/ci/travis/build.sh#L37

Any idea about what is wrong here ?

**Comment by brabalan** [comment]
Sorry, I don't know why this does not work.

**Comment by Insoleet** [comment]
Can you look at the difference between the releases of github and the builds you are doing manually ?

**Comment by brabalan** [comment]
The only difference is that I do a `cp -a`.

**Comment by Insoleet** [comment]
But in the .zip produced in both cases ? Can you download the github release and compare the result with your files ?

**Comment by brabalan** [comment]
The contents of the Contents/MacOS directories are quite different. In the release, there are many files with cpython-35m-darwin in the file name, where this part of the name is missing in my version. Also, there are files missing, for instance QtCore, which is why the binary does not launch:
```
ImportError: dlopen(/Applications/Sakia.app/Contents/MacOS/PyQt5.QtCore.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/QtCore
  Referenced from: /Applications/Sakia.app/Contents/MacOS/PyQt5.QtCore.cpython-35m-darwin.so
  Reason: image not found
```

Here is the full diff of that directory
```
Only in .: PyQt5
Only in /Applications/Sakia.app/Contents/MacOS: PyQt5.Qt.cpython-35m-darwin.so
Only in .: PyQt5.Qt.so
Only in /Applications/Sakia.app/Contents/MacOS: PyQt5.QtCore.cpython-35m-darwin.so
Only in .: PyQt5.QtCore.so
Only in /Applications/Sakia.app/Contents/MacOS: PyQt5.QtGui.cpython-35m-darwin.so
Only in .: PyQt5.QtGui.so
Only in /Applications/Sakia.app/Contents/MacOS: PyQt5.QtPrintSupport.cpython-35m-darwin.so
Only in .: PyQt5.QtPrintSupport.so
Only in /Applications/Sakia.app/Contents/MacOS: PyQt5.QtSvg.cpython-35m-darwin.so
Only in .: PyQt5.QtSvg.so
Only in /Applications/Sakia.app/Contents/MacOS: PyQt5.QtWidgets.cpython-35m-darwin.so
Only in .: PyQt5.QtWidgets.so
Binary files ./Python and /Applications/Sakia.app/Contents/MacOS/Python differ
Only in .: QtCore
Only in .: QtGui
Only in .: QtPrintSupport
Only in .: QtSvg
Only in .: QtWidgets
Only in /Applications/Sakia.app/Contents/MacOS: _bisect.cpython-35m-darwin.so
Only in .: _bisect.so
Only in /Applications/Sakia.app/Contents/MacOS: _bz2.cpython-35m-darwin.so
Only in .: _bz2.so
Only in /Applications/Sakia.app/Contents/MacOS: _codecs_cn.cpython-35m-darwin.so
Only in .: _codecs_cn.so
Only in /Applications/Sakia.app/Contents/MacOS: _codecs_hk.cpython-35m-darwin.so
Only in .: _codecs_hk.so
Only in /Applications/Sakia.app/Contents/MacOS: _codecs_iso2022.cpython-35m-darwin.so
Only in .: _codecs_iso2022.so
Only in /Applications/Sakia.app/Contents/MacOS: _codecs_jp.cpython-35m-darwin.so
Only in .: _codecs_jp.so
Only in /Applications/Sakia.app/Contents/MacOS: _codecs_kr.cpython-35m-darwin.so
Only in .: _codecs_kr.so
Only in /Applications/Sakia.app/Contents/MacOS: _codecs_tw.cpython-35m-darwin.so
Only in .: _codecs_tw.so
Only in /Applications/Sakia.app/Contents/MacOS: _ctypes.cpython-35m-darwin.so
Only in .: _ctypes.so
Only in /Applications/Sakia.app/Contents/MacOS: _datetime.cpython-35m-darwin.so
Only in .: _datetime.so
Only in /Applications/Sakia.app/Contents/MacOS: _decimal.cpython-35m-darwin.so
Only in .: _decimal.so
Only in /Applications/Sakia.app/Contents/MacOS: _elementtree.cpython-35m-darwin.so
Only in .: _elementtree.so
Only in /Applications/Sakia.app/Contents/MacOS: _hashlib.cpython-35m-darwin.so
Only in .: _hashlib.so
Only in /Applications/Sakia.app/Contents/MacOS: _heapq.cpython-35m-darwin.so
Only in .: _heapq.so
Only in /Applications/Sakia.app/Contents/MacOS: _json.cpython-35m-darwin.so
Only in .: _json.so
Only in .: _lzma.so
Only in /Applications/Sakia.app/Contents/MacOS: _md5.cpython-35m-darwin.so
Only in .: _md5.so
Only in /Applications/Sakia.app/Contents/MacOS: _multibytecodec.cpython-35m-darwin.so
Only in .: _multibytecodec.so
Only in /Applications/Sakia.app/Contents/MacOS: _multiprocessing.cpython-35m-darwin.so
Only in .: _multiprocessing.so
Only in /Applications/Sakia.app/Contents/MacOS: _opcode.cpython-35m-darwin.so
Only in .: _opcode.so
Only in /Applications/Sakia.app/Contents/MacOS: _pickle.cpython-35m-darwin.so
Only in .: _pickle.so
Only in /Applications/Sakia.app/Contents/MacOS: _posixsubprocess.cpython-35m-darwin.so
Only in .: _posixsubprocess.so
Only in /Applications/Sakia.app/Contents/MacOS: _random.cpython-35m-darwin.so
Only in .: _random.so
Only in /Applications/Sakia.app/Contents/MacOS: _scproxy.cpython-35m-darwin.so
Only in .: _scproxy.so
Only in /Applications/Sakia.app/Contents/MacOS: _sha1.cpython-35m-darwin.so
Only in .: _sha1.so
Only in /Applications/Sakia.app/Contents/MacOS: _sha256.cpython-35m-darwin.so
Only in .: _sha256.so
Only in /Applications/Sakia.app/Contents/MacOS: _sha512.cpython-35m-darwin.so
Only in .: _sha512.so
Only in /Applications/Sakia.app/Contents/MacOS: _socket.cpython-35m-darwin.so
Only in .: _socket.so
Only in /Applications/Sakia.app/Contents/MacOS: _sqlite3.cpython-35m-darwin.so
Only in .: _sqlite3.so
Only in /Applications/Sakia.app/Contents/MacOS: _ssl.cpython-35m-darwin.so
Only in .: _ssl.so
Only in /Applications/Sakia.app/Contents/MacOS: _struct.cpython-35m-darwin.so
Only in .: _struct.so
Only in /Applications/Sakia.app/Contents/MacOS: _yaml.cpython-35m-darwin.so
Only in /Applications/Sakia.app/Contents/MacOS: aiohttp._http_parser.cpython-35m-darwin.so
Only in .: aiohttp._http_parser.so
Only in /Applications/Sakia.app/Contents/MacOS: aiohttp._websocket.cpython-35m-darwin.so
Only in .: aiohttp._websocket.so
Only in /Applications/Sakia.app/Contents/MacOS: array.cpython-35m-darwin.so
Only in .: array.so
Binary files ./base_library.zip and /Applications/Sakia.app/Contents/MacOS/base_library.zip differ
Only in /Applications/Sakia.app/Contents/MacOS: binascii.cpython-35m-darwin.so
Only in .: binascii.so
Only in /Applications/Sakia.app/Contents/MacOS: certifi
Only in /Applications/Sakia.app/Contents/MacOS: fcntl.cpython-35m-darwin.so
Only in .: fcntl.so
Only in /Applications/Sakia.app/Contents/MacOS: grp.cpython-35m-darwin.so
Only in .: grp.so
Common subdirectories: ./include and /Applications/Sakia.app/Contents/MacOS/include
Common subdirectories: ./jsonschema and /Applications/Sakia.app/Contents/MacOS/jsonschema
Common subdirectories: ./lib and /Applications/Sakia.app/Contents/MacOS/lib
Common subdirectories: ./lib2to3 and /Applications/Sakia.app/Contents/MacOS/lib2to3
Only in .: liblzma.5.dylib
Only in /Applications/Sakia.app/Contents/MacOS: libyaml-0.2.dylib
Only in /Applications/Sakia.app/Contents/MacOS: math.cpython-35m-darwin.so
Only in .: math.so
Only in /Applications/Sakia.app/Contents/MacOS: mmap.cpython-35m-darwin.so
Only in .: mmap.so
Only in /Applications/Sakia.app/Contents/MacOS: multidict._multidict.cpython-35m-darwin.so
Only in .: multidict._multidict.so
Only in /Applications/Sakia.app/Contents/MacOS: pyexpat.cpython-35m-darwin.so
Only in .: pyexpat.so
Only in /Applications/Sakia.app/Contents/MacOS: qt5_plugins
Only in /Applications/Sakia.app/Contents/MacOS: readline.cpython-35m-darwin.so
Only in .: readline.so
Only in /Applications/Sakia.app/Contents/MacOS: resource.cpython-35m-darwin.so
Only in .: resource.so
Common subdirectories: ./sakia and /Applications/Sakia.app/Contents/MacOS/sakia
Binary files ./sakia.bin and /Applications/Sakia.app/Contents/MacOS/sakia.bin differ
Only in /Applications/Sakia.app/Contents/MacOS: select.cpython-35m-darwin.so
Only in .: select.so
Only in /Applications/Sakia.app/Contents/MacOS: sip.cpython-35m-darwin.so
Only in .: sip.so
Only in /Applications/Sakia.app/Contents/MacOS: termios.cpython-35m-darwin.so
Only in .: termios.so
Only in /Applications/Sakia.app/Contents/MacOS: unicodedata.cpython-35m-darwin.so
Only in .: unicodedata.so
Only in /Applications/Sakia.app/Contents/MacOS: yarl._quoting.cpython-35m-darwin.so
Only in .: yarl._quoting.so
Only in /Applications/Sakia.app/Contents/MacOS: zlib.cpython-35m-darwin.so
Only in .: zlib.so
```

**Comment by brabalan** [comment]
I'm sorry, but QtCore is still missing and this still does not launch. I suspect the problem is not in the copying of files, but in the fact that they are not there in the first place.

**Comment by Insoleet** [comment]
Looking at the build job logs : 
https://api.travis-ci.org/v3/job/344542961/log.txt
 I find these errors : 

```


16654 INFO: Looking for dynamic libraries

16659 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)

16659 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)

16661 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)

16661 ERROR: Can not find path ./QtSvg.framework/Versions/5/QtSvg (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)

16666 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.dylib)

16667 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.dylib)

16672 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtga.dylib)

16672 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtga.dylib)

16681 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)

16681 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)

16682 ERROR: Can not find path ./QtPrintSupport.framework/Versions/5/QtPrintSupport (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)

16682 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)

16690 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.dylib)

16691 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.dylib)

16698 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqgif.dylib)

16699 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqgif.dylib)

16703 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.dylib)

16704 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.dylib)

16711 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqjpeg.dylib)

16711 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqjpeg.dylib)

16716 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)

16716 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)

16717 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)

16717 ERROR: Can not find path ./QtSvg.framework/Versions/5/QtSvg (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)

16721 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqico.dylib)

16722 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqico.dylib)

16726 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqicns.dylib)

16726 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqicns.dylib)

16731 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwebp.dylib)

16731 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwebp.dylib)

16736 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqmacjp2.dylib)

16737 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqmacjp2.dylib)

16742 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)

16742 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)

16742 ERROR: Can not find path ./QtPrintSupport.framework/Versions/5/QtPrintSupport (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)

16743 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)

16747 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwbmp.dylib)

16747 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwbmp.dylib)

16855 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)

16856 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)

16856 ERROR: Can not find path ./QtPrintSupport.framework/Versions/5/QtPrintSupport (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)

16856 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)

16861 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtSvg.so)

16861 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtSvg.so)

16862 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtSvg.so)

16863 ERROR: Can not find path ./QtSvg.framework/Versions/5/QtSvg (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtSvg.so)

16868 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtGui.so)

16869 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtGui.so)

16901 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtWidgets.so)

16902 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtWidgets.so)

16902 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtWidgets.so)

16907 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/travis/.pyenv/versions/3.5.4/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/QtCore.so)
```

Did you install Qt differently than using  brew ?

Can you try to reproduce the commands run on travis and check the difference ? 
https://github.com/duniter/sakia/blob/master/ci/travis/build.sh
Thanks

**Comment by brabalan** [comment]
Two differences: I install qt and not qt5 (but looking at the formula I think it's the same). And before doing a `brew link --force qt` I first do a `brew install qt` (I'm not sure doing the link also does the installation).

**Comment by Insoleet** [comment]
Well I Install qt5 in the other script : https://github.com/duniter/sakia/blob/master/ci/travis/before_install.sh#L18 

What is the difference between qt5 and qt ? Can you try what happens when you install qt5 instead of qt ?

**Comment by brabalan** [comment]
Found it: it does not work with pyinstaller 3.2 but it works with 3.3.1. The log says you are using 3.2.

Some additional comments.
- https://github.com/duniter/sakia/blob/master/ci/travis/before_install.sh#L16 is no longer necessary (this tap is empty, it says so in the log)
- https://github.com/duniter/sakia/blob/master/ci/travis/before_install.sh#L21 gives an error (no such command update, same error in the log)
- the environment variable PYENV_PYTHON_VERSION is undefined for me, I guess it's defined as 3.5.4 somewhere else

**Comment by Insoleet** [comment]
I'm releasing 0.32.10post1 which implements all your suggested fixes. Can you try it when you find some time ?

**Comment by brabalan** [comment]
It works, thanks! If I may suggest a tiny cosmetic improvement: could you please directly compress the sakia.app directory, instead of the enclosing dist directory?
