### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Pafzedog** [duniter/sakia#778]
OS: kUbuntu 17.10
version : sakia 0.32.8
at first launch 
g1.db attached
```
An unhandled exception occured

    ----
    Traceback (most recent call last):

  File "sakia/main.py", line 116, in <module>

  File "site-packages/quamash/__init__.py", line 288, in run_until_complete

  File "asyncio/futures.py", line 294, in result

  File "asyncio/tasks.py", line 240, in _step

  File "sakia/app.py", line 164, in initialize_blockchain

  File "sakia/data/processors/blockchain.py", line 325, in initialize_blockchain

IndexError: list index out of range



```
[g1.db.zip](https://github.com/duniter/sakia/files/1687465/g1.db.zip)

**Comment by zicmama** [comment]
Sakia installed today.
Same issue, error is making reference to a file in "/home/travis"

Traceback (most recent call last):
  File "sakia/main.py", line 8, in <module>
  File "/home/travis/.pyenv/versions/3.5.4/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2
Failed to execute script main
LOADER: OK.
LOADER: Cleaning up Python interpreter.

**Comment by Insoleet** [comment]
Please look the following issue, a workaround is in there : https://github.com/duniter/sakia/issues/768

**Comment by Pafzedog** [comment]
I don't think it's the same bug for me.
workaround is not working

**Comment by zicmama** [comment]
sakia runs, but reach another error.

ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "sakia/main.py", line 116, in <module>
  File "site-packages/quamash/__init__.py", line 288, in run_until_complete
  File "asyncio/futures.py", line 294, in result
  File "asyncio/tasks.py", line 240, in _step
  File "sakia/app.py", line 164, in initialize_blockchain
  File "sakia/data/processors/blockchain.py", line 325, in initialize_blockchain
IndexError: list index out of range
Failed to execute script main

**Comment by Insoleet** [comment]
Pafzedog bug will be fixed in next release.
